import { StyleSheet, Platform } from 'react-native';
import {
  MUSCLE_DIAGRAM_HEIGHT,
  MUSCLE_DIAGRAM_WIDTH,
  MUSCLE_TAB_PANEL_MAX_HEIGHT,
  MUSCLE_TAB_PANEL_TOP_INSET,
} from '../constants/layout';
import { WORKOUT_THEME } from '../theme/workoutTheme';

const formsHistoryMuscleStyles = {
  inputSection: {
    width: '100%',
    marginBottom: 16,
  },
  label: {
    color: '#E6E8EC',
    fontSize: 16,
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  input: {
    width: '100%',
    backgroundColor: '#1B1E23',
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#2F343C',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    marginTop: 10,
  },
  exerciseHorizontalScroll: {
    marginBottom: 10,
  },
  exerciseSearchRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 12,
    paddingLeft: 14,
    paddingRight: 6,
    minHeight: 48,
  },
  exerciseSearchField: {
    flex: 1,
    paddingVertical: 12,
    paddingRight: 8,
    fontSize: 16,
  },
  exerciseSearchClearButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseSearchClearText: {
    fontSize: 18,
    fontWeight: '600',
  },
  dropdownButton: {
    width: '100%',
    backgroundColor: '#1B1E23',
    borderWidth: 1,
    borderColor: '#2F343C',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  dropdownChevron: {
    color: '#9AA1AC',
    fontSize: 14,
  },
  dropdownList: {
    width: '100%',
    backgroundColor: '#1B1E23',
    borderWidth: 1,
    borderColor: '#2F343C',
    borderRadius: 12,
    marginTop: 10,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2F343C',
  },
  dropdownItemText: {
    color: '#E6E8EC',
    fontSize: 16,
  },
  exerciseScrollContent: {
    paddingVertical: 4,
    paddingRight: 8,
    gap: 10,
  },
  exerciseCard: {
    width: 104,
    height: 104,
    borderWidth: 1,
    borderRadius: 18,
    padding: 8,
    justifyContent: 'space-between',
  },
  exerciseCardSelected: {
    borderWidth: 2,
    borderColor: '#3B82F6',
  },
  exerciseCardSelectedWorkout: {
    borderWidth: 2,
    borderColor: WORKOUT_THEME.selectedExerciseBorder,
  },
  exerciseCardTop: {
    flex: 1,
    borderRadius: 10,
  },
  exerciseCardLabel: {
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 6,
  },
  repsValue: {
    color: '#FFFFFF',
    fontSize: 52,
    fontWeight: '700',
    marginBottom: 12,
  },
  modeSwitchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    marginBottom: 12,
    paddingLeft: 4,
  },
  notepadHint: {
    fontSize: 13,
    marginBottom: 8,
    alignSelf: 'stretch',
  },
  notepadOuter: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 12,
    marginBottom: 4,
  },
  notepadExerciseTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
  },
  notepadSectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 4,
  },
  notepadStoredScroll: {
    maxHeight: 220,
    marginBottom: 12,
  },
  notepadTwinRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
    marginBottom: 12,
  },
  notepadTwinField: {
    flex: 1,
    minHeight: 32,
    maxHeight: 36,
    paddingVertical: 4,
    paddingHorizontal: 8,
    fontSize: 17,
    fontWeight: '600',
  },
  notepadTwinFieldWeight: {
    paddingRight: 2,
  },
  notepadTwinFor: {
    fontSize: 15,
    fontWeight: '600',
    flexShrink: 0,
    marginLeft: -2,
  },
  notepadRepeatButton: {
    flexShrink: 0,
    marginLeft: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notepadRepeatButtonDisabled: {
    opacity: 0.38,
  },
  notepadRepeatIcon: {
    width: 28,
    height: 28,
  },
  repsButtonsRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  arrowButton: {
    width: 100,
    height: 72,
    borderRadius: 14,
    backgroundColor: '#2A2F38',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowText: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '700',
  },
  primaryButton: {
    width: '100%',
    backgroundColor: '#3B82F6',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  secondaryButton: {
    width: '100%',
    backgroundColor: '#252A32',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 20,
  },
  secondaryButtonText: {
    color: '#E6E8EC',
    fontSize: 18,
    fontWeight: '700',
  },
  weightButtonsRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  weightButton: {
    flex: 1,
    backgroundColor: '#2A2F38',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  weightButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  savedSetsSection: {
    width: '100%',
    backgroundColor: '#171A1F',
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  savedSetsTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
  },
  emptyText: {
    color: '#9AA1AC',
    fontSize: 15,
  },
  movementCard: {
    backgroundColor: '#1E232B',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  historyCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyScreenScroll: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    alignItems: 'center',
  },
  historySubtitle: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
    alignSelf: 'stretch',
  },
  historyStatCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    marginBottom: 14,
    alignSelf: 'center',
  },
  historyCardTitle: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 10,
  },
  historyWeightHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  historyAddWeightButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyAddWeightButtonText: {
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '700',
    marginTop: -1,
  },
  historyWeightTabsRow: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 10,
  },
  historyWeightTabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
  },
  historyWeightTabText: {
    fontSize: 13,
    fontWeight: '700',
  },
  historyWeightEntriesWrap: {
    width: '100%',
    gap: 8,
  },
  historyWeightEntryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  historyWeightEntryTextBlock: {
    flex: 1,
  },
  historyWeightEntryValue: {
    fontSize: 15,
    fontWeight: '700',
  },
  historyWeightEntryDate: {
    fontSize: 12,
    marginTop: 2,
  },
  historyWeightEntryActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  historyWeightEntryActionBtn: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  historyWeightEntryEditText: {
    fontSize: 12,
    fontWeight: '700',
  },
  historyWeightEntryDeleteText: {
    fontSize: 12,
    fontWeight: '700',
  },
  weightDatePickerTrigger: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  weightDatePickerTriggerLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  weightDatePickerTriggerValue: {
    fontSize: 17,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  weightLogModalContentWrap: {
    width: '100%',
    alignItems: 'center',
  },
  weightDateInlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  weightDateBottomSheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  weightDateBottomSheetBackdropTouch: {
    flex: 1,
  },
  weightDateBottomSheetCard: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderBottomWidth: 0,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 16,
  },
  weightDateBottomSheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  weightDatePickersRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  weightDatePickerColumn: {
    flex: 1,
    minWidth: 0,
  },
  weightDatePickerYearColumn: {
    flex: 1.2,
  },
  weightDatePickerColumnLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
    textAlign: 'center',
  },
  weightDatePickerWheel: {
    width: '100%',
    height: Platform.OS === 'ios' ? 150 : 120,
  },
  weightDatePickerItem: {
    fontSize: 18,
  },
  historyModeSwitch: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 10,
  },
  historyModeSwitchOption: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyModeSwitchText: {
    fontSize: 13,
    fontWeight: '700',
  },
  historyPeriodControlsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  historySwitchCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  historySwitchLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 6,
    textAlign: 'center',
  },
  historySwitchControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  historySwitchButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historySwitchButtonText: {
    fontSize: 22,
    fontWeight: '700',
    marginTop: -2,
  },
  historySwitchValue: {
    flex: 1,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  historyStatLine: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  historyStatEmphasis: {
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  historyStatCaption: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  historyCalendarCard: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    backgroundColor: 'rgba(93, 85, 216, 0.72)',
    padding: 14,
    marginBottom: 16,
  },
  historyCalendarTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  historyCalendarNavBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  historyCalendarNavBtnText: {
    fontSize: 22,
    fontWeight: '700',
    marginTop: -2,
  },
  historyCalendarMonthTitle: {
    fontSize: 16,
    fontWeight: '800',
    flex: 1,
    textAlign: 'center',
  },
  historyCalendarWeekHeader: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  historyCalendarWeekHeaderLetter: {
    width: '14.2857%',
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '700',
  },
  historyCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  historyCalendarDaySlot: {
    width: '14.2857%',
    paddingVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyCalendarDayInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyCalendarDayMuted: {
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
  },
  /** Slight dim on leading/trailing days from previous/next month (still filled, not blank). */
  historyCalendarDayAdjacentMonth: {
    opacity: 0.72,
  },
  historyCalendarDayHasWorkout: {},
  historyCalendarDayTodayRing: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.55)',
  },
  historyCalendarDayNumber: {
    fontSize: 14,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  historyCalendarDayNumberOnAccent: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  historyPastWorkoutsHeading: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: 'rgba(238, 241, 255, 0.55)',
    alignSelf: 'flex-start',
    width: '100%',
    maxWidth: 420,
    marginBottom: 8,
    marginTop: 4,
  },
  historyProgressScroll: {
    paddingTop: 4,
    paddingHorizontal: 0,
    alignItems: 'center',
    width: '100%',
  },
  historyProgressTopBarSide: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyProgressTitleCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyProgressCloseText: {
    fontSize: 20,
    fontWeight: '700',
  },
  historyProgressSegmentBar: {
    flexDirection: 'row',
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    marginBottom: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
    overflow: 'hidden',
  },
  historyProgressSegmentOption: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    paddingHorizontal: 6,
  },
  historyProgressSegmentOptionActive: {
    backgroundColor: 'rgba(124, 116, 232, 0.98)',
  },
  historyProgressSegmentText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(238, 241, 255, 0.72)',
  },
  historyProgressSegmentTextActive: {
    color: '#FFFFFF',
  },
  strengthScoreCard: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    marginBottom: 16,
  },
  strengthScoreCardCompact: {
    marginBottom: 14,
  },
  strengthScoreHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  strengthScoreTitle: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  strengthScoreLevelPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  strengthScoreLevelPillText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  strengthScoreValue: {
    fontSize: 48,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    marginBottom: 8,
  },
  strengthScoreLevelTrack: {
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 10,
  },
  strengthScoreLevelFill: {
    height: '100%',
    borderRadius: 3,
  },
  strengthScoreCaption: {
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 10,
  },
  strengthScorePillarRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 8,
  },
  strengthScorePillar: {
    fontSize: 12,
    fontWeight: '600',
  },
  strengthScoreMeta: {
    fontSize: 12,
    lineHeight: 17,
  },
  strengthScoreMovementsButton: {
    marginTop: 12,
    alignSelf: 'flex-start',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  strengthScoreMovementsButtonText: {
    color: '#EEF1FF',
    fontSize: 14,
    fontWeight: '700',
  },
  strengthMovementsScreenShell: {
    position: 'relative',
    overflow: 'hidden',
  },
  movementsAccordionList: {
    width: '100%',
    gap: 0,
  },
  movementsAccordionSection: {
    width: '100%',
    marginBottom: 2,
  },
  movementsAccordionSectionNested: {
    marginTop: 10,
    marginBottom: 4,
    marginLeft: 8,
    width: 'auto',
  },
  movementsAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.12)',
  },
  movementsAccordionHeaderNested: {
    paddingVertical: 12,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  movementsAccordionHeaderExpanded: {
    borderBottomColor: 'rgba(93, 85, 216, 0.45)',
  },
  movementsAccordionChevron: {
    width: 22,
    color: 'rgba(238, 241, 255, 0.55)',
    fontSize: 22,
    fontWeight: '700',
    marginRight: 10,
  },
  movementsAccordionChevronNested: {
    fontSize: 18,
    width: 18,
    marginRight: 8,
  },
  movementsAccordionLabel: {
    flex: 1,
    color: '#EEF1FF',
    fontSize: 17,
    fontWeight: '700',
  },
  movementsAccordionLabelNested: {
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(238, 241, 255, 0.72)',
  },
  movementsAccordionCount: {
    color: 'rgba(238, 241, 255, 0.45)',
    fontSize: 14,
    fontWeight: '600',
    minWidth: 28,
    textAlign: 'right',
  },
  movementsAccordionBody: {
    paddingTop: 10,
    paddingBottom: 14,
    paddingLeft: 4,
  },
  movementsAccordionBodyNested: {
    paddingTop: 8,
    paddingBottom: 4,
    paddingLeft: 8,
  },
  movementsAccordionEmpty: {
    color: 'rgba(238, 241, 255, 0.55)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
    paddingRight: 8,
  },
  movementsResultCount: {
    color: 'rgba(238, 241, 255, 0.5)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 10,
  },
  movementsRecentStripBlock: {
    width: '100%',
    marginBottom: 18,
    marginHorizontal: -4,
  },
  movementsRecentStripHeading: {
    color: 'rgba(238, 241, 255, 0.55)',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  movementsRecentScrollContent: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingVertical: 4,
    paddingLeft: 4,
    paddingRight: 16,
    gap: 10,
  },
  movementsRecentScrollCard: {
    width: 168,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(93, 85, 216, 0.45)',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  movementsRecentScrollChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingLeft: 6,
    paddingRight: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(28, 30, 36, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    marginBottom: 10,
    maxWidth: '100%',
  },
  movementsRecentScrollIconWell: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: 'rgba(62, 65, 76, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  movementsRecentScrollIcon: {
    width: 34,
    height: 34,
  },
  movementsRecentScrollChipLabel: {
    marginLeft: 6,
    color: 'rgba(238, 241, 255, 0.9)',
    fontSize: 12,
    fontWeight: '700',
    flexShrink: 1,
  },
  movementsRecentScrollTitle: {
    color: '#EEF1FF',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 19,
    marginBottom: 10,
    minHeight: 38,
  },
  movementsRecentScrollMaxBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: 'center',
    marginBottom: 8,
  },
  movementsRecentScrollMaxCaption: {
    color: 'rgba(238, 241, 255, 0.5)',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  movementsRecentScrollMaxRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
  },
  movementsRecentScrollMaxValue: {
    color: '#EEF1FF',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 30,
    fontVariant: ['tabular-nums'],
  },
  movementsRecentScrollMaxUnit: {
    color: 'rgba(238, 241, 255, 0.72)',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 4,
    textTransform: 'lowercase',
  },
  movementsRecentScrollDate: {
    color: 'rgba(238, 241, 255, 0.55)',
    fontSize: 11,
    fontWeight: '600',
  },
  strengthMovementSearchRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 12,
    backgroundColor: 'rgba(93, 85, 216, 0.55)',
    paddingLeft: 14,
    paddingRight: 6,
    minHeight: 48,
    marginBottom: 16,
  },
  strengthMovementSearchField: {
    flex: 1,
    paddingVertical: 12,
    paddingRight: 8,
    fontSize: 16,
    color: '#EEF1FF',
  },
  strengthMovementSearchClear: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  strengthMovementSearchClearText: {
    fontSize: 18,
    fontWeight: '600',
    color: 'rgba(238, 241, 255, 0.72)',
  },
  strengthMovementCard: {
    marginBottom: 12,
    overflow: 'hidden',
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  strengthMovementCardUnlogged: {
    opacity: 0.48,
    backgroundColor: 'rgba(30, 32, 38, 0.85)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  strengthMovementTextUnlogged: {
    color: 'rgba(238, 241, 255, 0.42)',
  },
  strengthMovementCardTopRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    marginBottom: 12,
  },
  /** Same look as home split-day muscle chips (`dashboardTargetMuscleChip`). */
  strengthMovementMuscleChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(28, 30, 36, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    flexShrink: 0,
  },
  strengthMovementMuscleChipPlaceholder: {
    paddingHorizontal: 12,
    minHeight: 56,
    justifyContent: 'center',
  },
  strengthMovementMuscleIconWell: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: 'rgba(62, 65, 76, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  strengthMovementMuscleIcon: {
    width: 48,
    height: 48,
  },
  strengthMovementMuscleTextCol: {
    marginLeft: 8,
    justifyContent: 'center',
    maxWidth: 72,
  },
  strengthMovementMuscleChipLabel: {
    color: 'rgba(238, 241, 255, 0.95)',
    fontSize: 14,
    fontWeight: '700',
  },
  strengthMovementTitleCol: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'space-between',
  },
  strengthMovementCardTitle: {
    color: '#EEF1FF',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
    marginBottom: 8,
    flexShrink: 1,
  },
  strengthMovementFavoriteButton: {
    width: 40,
    height: 40,
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
  },
  strengthMovementFavoriteIcon: {
    fontSize: 22,
    color: 'rgba(238, 241, 255, 0.45)',
  },
  strengthMovementFavoriteIconOn: {
    color: '#F5C542',
  },
  strengthMovementNotLoggedHint: {
    marginBottom: 0,
  },
  strengthMovementMaxBox: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 14,
    alignItems: 'center',
  },
  strengthMovementMaxCaption: {
    color: 'rgba(238, 241, 255, 0.55)',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  strengthMovementMaxValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 6,
  },
  strengthMovementMaxValue: {
    color: '#EEF1FF',
    fontSize: 48,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    lineHeight: 52,
  },
  strengthMovementMaxUnit: {
    color: 'rgba(238, 241, 255, 0.72)',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
    textTransform: 'lowercase',
  },
  strengthMovementRecentHeading: {
    marginTop: 4,
    marginBottom: 8,
  },
  strengthMovementSetLine: {
    color: 'rgba(238, 241, 255, 0.88)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
  },
  historySectionHeading: {
    fontSize: 17,
    fontWeight: '800',
    marginTop: 10,
    marginBottom: 12,
    alignSelf: 'flex-start',
    width: '100%',
    maxWidth: 420,
  },
  deleteText: {
    color: '#FF7C7C',
    fontSize: 14,
    fontWeight: '700',
  },
  movementTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  historyMovementBlock: {
    marginTop: 8,
  },
  historyMovementTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  setText: {
    color: '#D8DDE6',
    fontSize: 14,
    marginBottom: 2,
  },
  storedSetRow: {
    marginBottom: 10,
  },
  storedSetActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
    marginBottom: 6,
  },
  smallActionButton: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  smallActionButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  smallDeleteButton: {
    backgroundColor: '#7F1D1D',
  },
  smallDeleteButtonText: {
    color: '#FECACA',
    fontSize: 12,
    fontWeight: '700',
  },
  editSetPanel: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginTop: 4,
  },
  editSetInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    marginBottom: 8,
  },
  editSetActions: {
    flexDirection: 'row',
    gap: 8,
  },
  logSheetSetListRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingBottom: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  logSheetSetListNumber: {
    width: 36,
    fontSize: 26,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    color: '#EEF1FF',
    paddingTop: 18,
    marginRight: 6,
  },
  logSheetSetListMain: {
    flex: 1,
    minWidth: 0,
  },
  logSheetSetListValuesRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    flexWrap: 'nowrap',
    gap: 8,
  },
  logSheetSetListFieldCol: {
    flex: 1,
    minWidth: 0,
  },
  logSheetSetListFieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 6,
    opacity: 0.75,
  },
  logSheetSetListValueBox: {
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  logSheetSetListValueText: {
    fontSize: 20,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  logSheetSetListAt: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 10,
    opacity: 0.55,
  },
  logSheetSetListMeta: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
    opacity: 0.5,
  },
  logSheetSetListActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  endButton: {
    width: '100%',
    backgroundColor: '#DC2626',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  endButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  workoutCloseButton: {
    position: 'absolute',
    top: 4,
    left: 8,
    zIndex: 20,
    width: 44,
    height: 44,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  workoutCloseButtonText: {
    fontSize: 28,
    fontWeight: '400',
    lineHeight: 32,
  },
  summaryTitle: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '700',
    marginBottom: 14,
  },
  summaryStat: {
    color: '#E6E8EC',
    fontSize: 18,
    marginBottom: 8,
  },
  musclePulloutRow: {
    position: 'absolute',
    top: MUSCLE_TAB_PANEL_TOP_INSET,
    right: 0,
    flexDirection: 'row',
    alignItems: 'flex-start',
    maxHeight: MUSCLE_TAB_PANEL_MAX_HEIGHT,
    minHeight: 80,
  },
  musclePulloutHandle: {
    width: 44,
    marginTop: 18,
    paddingVertical: 14,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  musclePulloutHandleGrip: {
    width: 4,
    height: 22,
    borderRadius: 2,
    opacity: 0.85,
  },
  musclePulloutDrawer: {
    overflow: 'hidden',
    borderLeftWidth: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    maxHeight: MUSCLE_TAB_PANEL_MAX_HEIGHT,
  },
  muscleTabContent: {
    maxHeight: MUSCLE_TAB_PANEL_MAX_HEIGHT,
  },
  muscleTabContentContainer: {
    padding: 12,
    paddingTop: 12,
    paddingBottom: 10,
    flexGrow: 0,
  },
  muscleTabTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  muscleGroupLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 4,
    marginBottom: 4,
  },
  musclePulloutDiagramWrap: {
    width: '100%',
    marginBottom: 10,
    position: 'relative',
    alignSelf: 'center',
  },
  muscleDiagramImage: {
    width: MUSCLE_DIAGRAM_WIDTH,
    height: MUSCLE_DIAGRAM_HEIGHT,
    resizeMode: 'contain',
    marginBottom: 16,
  },
  muscleDiagramWrap: {
    width: MUSCLE_DIAGRAM_WIDTH,
    height: MUSCLE_DIAGRAM_HEIGHT,
    marginBottom: 16,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  muscleZoneButton: {
    position: 'absolute',
    width: 12,
    height: 12,
    marginLeft: -6,
    marginTop: -6,
    backgroundColor: 'rgba(59,130,246,0.85)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.95)',
    borderRadius: 6,
  },
  muscleSideToggleRow: {
    width: '100%',
    flexDirection: 'row',
    borderRadius: 12,
    borderWidth: 1,
    padding: 4,
    marginBottom: 12,
    maxWidth: 360,
  },
  muscleSideToggleButton: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  muscleSideToggleText: {
    fontSize: 14,
    fontWeight: '700',
  },
  muscleModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  muscleModalBackdropTouch: {
    ...StyleSheet.absoluteFillObject,
  },
  muscleModalCard: {
    width: '100%',
    maxWidth: 430,
    maxHeight: '75%',
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
  },
  muscleModalScroll: {
    maxHeight: 360,
    marginBottom: 12,
  },
  muscleModalContent: {
    paddingBottom: 8,
  },
  targetsPresetRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  targetsPresetChip: {
    flexGrow: 1,
    flexBasis: '45%',
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  targetsPresetChipTitle: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  targetsPresetChipSubtitle: {
    fontSize: 12,
    lineHeight: 16,
  },
  targetsSwapRow: {
    marginBottom: 6,
  },
  targetsSwapButton: {
    alignSelf: 'flex-start',
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  targetsSwapButtonText: {
    fontSize: 14,
    fontWeight: '700',
  },
  targetsSwapHint: {
    fontSize: 13,
    marginTop: 8,
  },
  targetsDayCard: {
    flexDirection: 'column',
    alignItems: 'stretch',
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  targetsCategoryMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 12,
  },
  targetsCategoryTextBlock: {
    flexShrink: 0,
  },
  targetsCategoryBarWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  targetsCategoryBarTrack: {
    height: 12,
    borderRadius: 6,
    borderWidth: 1,
    overflow: 'visible',
    width: '100%',
    position: 'relative',
  },
  targetsCategoryBarFillSolid: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
  },
  targetsCategoryBarPill: {
    position: 'absolute',
    width: 18,
    height: 12,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    top: '50%',
    marginTop: -6,
    zIndex: 2,
  },
  targetsDayCardLeft: {
    width: 72,
    paddingRight: 8,
  },
  targetsDayName: {
    fontSize: 16,
    fontWeight: '800',
  },
  targetsDaySessionLabel: {
    fontSize: 13,
    marginTop: 2,
    fontWeight: '600',
  },
  targetsDayCardRight: {
    flex: 1,
    minHeight: 60,
  },
  targetsMiniDiagramRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  targetsMiniDiagramHalf: {
    flex: 1,
    maxWidth: '50%',
  },
  targetsMiniDiagramRest: {
    flex: 1,
    minHeight: 52,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  targetsMiniDiagramRestText: {
    fontSize: 22,
    color: 'rgba(238, 241, 255, 0.35)',
    fontWeight: '300',
  },
  targetsPickerCard: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
  },
  targetsPickerRow: {
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  targetsPickerRowLabel: {
    fontSize: 16,
    fontWeight: '700',
  },
  targetsGoalBarTrack: {
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
    marginTop: 8,
    overflow: 'hidden',
    width: '100%',
  },
  targetsGoalBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  targetsLastWorkoutCard: {
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  targetsSubcategoryToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  targetsSubcategoryToggleText: {
    fontSize: 13,
    fontWeight: '700',
  },
  targetsSubcategoryChevron: {
    fontSize: 12,
    marginRight: 8,
    width: 16,
  },
  targetsSubcategoryList: {
    marginTop: 4,
    marginBottom: 4,
    paddingLeft: 4,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.12)',
    paddingTop: 8,
  },
  targetsSubcategoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  targetsSubcategoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
  },
  targetsSubcategoryName: {
    fontSize: 14,
    fontWeight: '600',
  },
  targetsSubcategorySets: {
    fontSize: 13,
    fontWeight: '800',
  },
  targetsSubcategoryTargetMuted: {
    fontSize: 13,
    fontWeight: '600',
  },
  splitTargetsEntry: {
    width: '100%',
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  splitTargetsEntryLabel: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  splitTargetsEntryChevron: {
    fontSize: 20,
    fontWeight: '600',
  },
  targetsSplitWeekStrip: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 6,
    marginBottom: 12,
  },
  targetsSplitWeekCell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  targetsSplitWeekCellToday: {
    alignSelf: 'stretch',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 8,
    marginVertical: -6,
    paddingHorizontal: 3,
  },
  targetsSplitWeekLetter: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  targetsSplitWeekLetterToday: {
    fontWeight: '900',
  },
  targetsSplitWeekWeightIcon: {
    width: 22,
    height: 22,
    marginTop: 4,
  },
  targetsSplitWeekStreakIcon: {
    width: 22,
    height: 22,
    marginTop: 4,
  },
  targetsSplitWeekRestCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    marginTop: 7,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.45)',
    backgroundColor: 'transparent',
  },
  targetsSplitWeekRestCircleToday: {
    borderColor: '#FFFFFF',
  },
  targetsPplRingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
    marginBottom: 14,
    paddingHorizontal: 2,
    gap: 6,
  },
  targetsPplRingCell: {
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  targetsPplRingLabel: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '800',
  },
  splitPlannerScreen: {
    flex: 1,
  },
  splitPlannerDayCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    width: '100%',
  },
  splitPlannerDayLeft: {
    width: 88,
    paddingRight: 8,
  },
  splitPlannerDayName: {
    fontSize: 16,
    fontWeight: '800',
  },
  splitPlannerDayType: {
    fontSize: 13,
    marginTop: 3,
    fontWeight: '600',
  },
  splitPlannerDayRight: {
    flex: 1,
    minHeight: 52,
  },
  splitPlannerMiniRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  splitPlannerMiniHalf: {
    flex: 1,
    maxWidth: '50%',
  },
  splitPlannerMiniRest: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  splitPlannerMiniRestText: {
    fontSize: 20,
    color: 'rgba(238, 241, 255, 0.35)',
  },
  splitPlannerModalCard: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '88%',
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
  },
  splitPlannerTypeRow: {
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  splitPlannerTypeRowLabel: {
    fontSize: 16,
    fontWeight: '700',
  },
  splitPlannerMuscleWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  splitPlannerMuscleChip: {
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  splitPlannerMuscleChipText: {
    fontSize: 13,
    fontWeight: '600',
  },
  splitPlannerModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  splitPlannerModalButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 12,
    alignItems: 'center',
  },
  splitPlannerModalButtonText: {
    fontSize: 16,
    fontWeight: '700',
  },
};
export default formsHistoryMuscleStyles;
