import { StyleSheet } from 'react-native';
import { GAME_THEME_DARK } from '../theme/gameTheme';

/** @param {typeof GAME_THEME_DARK} theme */
export function createHomeDashboardStyles(theme) {
  return {
    homeScreenScrollWrap: {
      flex: 1,
      backgroundColor: theme.screenBg,
      overflow: 'hidden',
    },
    homeScreenScroll: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    homeScreenContent: {
      overflow: 'visible',
    },
    homeScreenContentGrow: {
      flexGrow: 1,
    },
    homeProfileHeaderBar: {
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 10,
    },
    homeTopHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      position: 'relative',
    },
    homeTopHeaderLeft: {
      flex: 1,
      alignItems: 'flex-start',
      gap: 10,
      paddingRight: 12,
    },
    homeSessionTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.textPrimary,
      letterSpacing: -0.3,
    },
    homeTopDateCol: {
      alignItems: 'flex-end',
    },
    homeTopDateWeekday: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.5,
      color: theme.textMuted,
    },
    homeTopDateNumber: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.textPrimary,
      marginTop: -2,
    },
    homeTopBackToTodayButton: {
      position: 'absolute',
      right: 0,
      // Profile button (36) + column gap (10) aligns with session title row.
      top: 46,
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
    },
    homeTopBackToTodayButtonHidden: {
      opacity: 0,
    },
    homeTopBackToTodayText: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 26,
      marginTop: -1,
      color: theme.navAccent,
    },
    homeGamifiedSection: {
      position: 'relative',
      zIndex: 0,
      paddingHorizontal: 16,
      paddingTop: 58,
      paddingBottom: 28,
      backgroundColor: 'transparent',
      overflow: 'visible',
    },
    homeBodyPanelWrap: {
      flexGrow: 1,
      position: 'relative',
      zIndex: 2,
      overflow: 'visible',
      backgroundColor: 'transparent',
    },
    homeBodyPanelGlow: {
      position: 'absolute',
      top: -148,
      left: 0,
      right: 0,
      height: 280,
      zIndex: 0,
    },
    homeBodyPanel: {
      flexGrow: 1,
      position: 'relative',
      zIndex: 1,
      paddingTop: 28,
      paddingHorizontal: 16,
      backgroundColor: theme.homeBodyPanelBg,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      borderWidth: 1,
      borderBottomWidth: 0,
      borderColor: theme.borderSubtle,
      gap: 18,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 8,
    },
    homeDateStripWrap: {
      width: '100%',
      marginHorizontal: -8,
    },
    homeDateStripList: {
      paddingHorizontal: 8,
    },
    homeDateCell: {
      width: 56,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
    },
    homeDateCellInner: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 48,
      minHeight: 72,
      borderRadius: 20,
      overflow: 'hidden',
      paddingVertical: 8,
    },
    homeDateCellGlass: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.homeGlassBubbleBorder,
      backgroundColor: theme.homeGlassBubble,
    },
    homeDateWeekday: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.6,
      color: theme.textMuted,
      marginBottom: 4,
    },
    homeDateWeekdaySelected: {
      color: theme.textPrimary,
    },
    homeDateNumber: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    homeDateNumberSelected: {
      color: theme.textPrimary,
    },
    homeDateDot: {
      width: 5,
      height: 5,
      borderRadius: 3,
      marginTop: 6,
      backgroundColor: 'transparent',
    },
    homeDateDotLogged: {
      backgroundColor: theme.textPrimary,
    },
    homeLevelSelectWrap: {
      width: '100%',
      alignItems: 'center',
      minHeight: 120,
      flexDirection: 'column',
      paddingTop: 16,
      paddingBottom: 8,
      overflow: 'visible',
    },
    homeLevelSelectIconTrack: {
      paddingBottom: 0,
      overflow: 'visible',
    },
    homeLevelCircleCell: {
      width: 104,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 98,
      paddingVertical: 6,
      overflow: 'visible',
    },
    homeLevelSelectedRing: {
      position: 'absolute',
      zIndex: 0,
    },
    homeLevelSelectedRingIcon: {
      width: 86,
      height: 86,
      borderRadius: 43,
      top: 6,
      left: 6,
    },
    homeLevelSelectedRingRest: {
      width: 62,
      height: 62,
      borderRadius: 31,
      top: 5,
      left: 5,
    },
    homeLevelDayDateOverlay: {
      position: 'absolute',
      top: 18,
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 3,
    },
    homeLevelDayDateOverlayRest: {
      position: 'relative',
      top: 0,
    },
    homeLevelDayWeekdayRest: {
      fontSize: 6,
      color: 'rgba(255, 255, 255, 0.55)',
    },
    homeLevelDayNumberRest: {
      fontSize: 11,
      color: 'rgba(255, 255, 255, 0.7)',
    },
    homeLevelDayWeekday: {
      fontSize: 8,
      fontWeight: '700',
      letterSpacing: 0.4,
      color: '#FFFFFF',
      opacity: 0.92,
    },
    homeLevelDayNumber: {
      fontSize: 16,
      fontWeight: '800',
      color: '#FFFFFF',
      marginTop: -1,
      opacity: 0.95,
    },
    homeLevelRestWrap: {
      width: 72,
      height: 72,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'visible',
    },
    homeLevelTodayStarWrap: {
      position: 'absolute',
      top: 16,
      left: 0,
      right: 0,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 3,
    },
    homeLevelTodayStarWrapRest: {
      position: 'relative',
      top: 0,
    },
    homeLevelTodayStar: {
      fontSize: 28,
      lineHeight: 30,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    homeLevelTodayStarRest: {
      fontSize: 18,
      lineHeight: 20,
      color: 'rgba(255, 255, 255, 0.75)',
    },
    homeLevelCircleRest: {
      width: 50,
      height: 50,
      borderRadius: 25,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(75, 85, 99, 0.32)',
    },
    homeLevelCircleSmall: {
      width: 84,
      height: 84,
      borderRadius: 42,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.homeGamifiedInactive,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.38,
      shadowRadius: 6,
      elevation: 6,
    },
    homeLevelCircleSmallBottom: {
      position: 'absolute',
      bottom: -5,
      left: 8,
      right: 8,
      height: 12,
      borderRadius: 6,
      backgroundColor: 'rgba(0,0,0,0.28)',
    },
    homeLevelCircleLarge: {
      width: 88,
      height: 88,
      borderRadius: 44,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 6,
      elevation: 6,
    },
    homeLevelCircleLargeBottom: {
      position: 'absolute',
      bottom: -4,
      left: 8,
      right: 8,
      height: 12,
      borderRadius: 6,
      backgroundColor: 'rgba(0,0,0,0.3)',
    },
    homeLevelStar: {
      fontSize: 32,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    homeLevelIconShell: {
      width: 98,
      height: 98,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'visible',
    },
    homeLevelIconWrap: {
      width: 72,
      height: 72,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 36,
      position: 'relative',
      overflow: 'visible',
    },
    homeLevelIconImage: {
      width: 72,
      height: 72,
    },
    homeLevelIconMuted: {
      opacity: 0.42,
    },
    homeLevelStarSmall: {
      fontSize: 34,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    homeLevelStarMuted: {
      opacity: 0.72,
    },
    homeLevelRestIcon: {
      fontSize: 22,
      color: 'rgba(255,255,255,0.7)',
    },
    homeLevelRestIconSmall: {
      fontSize: 18,
      color: 'rgba(255,255,255,0.32)',
      fontWeight: '500',
    },
    homeStatsBar: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      backgroundColor: theme.homeStatBarBg,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
    },
    homeStatCell: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    homeStatCellTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    homeStatIconWell: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.iconWellBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeStatIcon: {
      width: 16,
      height: 16,
      tintColor: theme.navAccent,
      resizeMode: 'contain',
    },
    homeStatCheckMark: {
      fontSize: 15,
      fontWeight: '800',
      color: theme.navAccent,
      lineHeight: 16,
    },
    homeStatValue: {
      fontSize: 20,
      fontWeight: '800',
      fontStyle: 'italic',
      color: theme.textPrimary,
      letterSpacing: -0.5,
    },
    homeStatLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textMuted,
      textAlign: 'center',
      letterSpacing: 0.15,
    },
    homeCarouselWrap: {
      borderRadius: 16,
      backgroundColor: theme.homeCarouselBg,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      overflow: 'hidden',
    },
    homeCarouselPage: {
      width: '100%',
      minHeight: 88,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    homeCarouselTextCol: {
      flex: 1,
    },
    homeCarouselValue: {
      fontSize: 28,
      fontWeight: '800',
      color: theme.textPrimary,
      letterSpacing: -0.5,
    },
    homeCarouselLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: theme.textMuted,
      marginTop: 2,
    },
    homeCarouselBadge: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.streakGold,
    },
    homeCarouselBadgeImage: {
      width: 36,
      height: 36,
      resizeMode: 'contain',
    },
    homeCarouselRankImage: {
      width: 52,
      height: 52,
      resizeMode: 'contain',
    },
    homeCarouselDots: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 6,
      paddingTop: 8,
      paddingBottom: 10,
    },
    homeMovementSection: {
      gap: 10,
    },
    homeMovementSectionTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 2,
    },
    homeMovementCard: {
      backgroundColor: theme.cardBg,
      borderRadius: 14,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
    },
    homeMovementCardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 8,
    },
    homeMovementChipWell: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.chipWellBg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.chipWellBorder,
    },
    homeMovementChipIcon: {
      width: 28,
      height: 28,
      resizeMode: 'contain',
    },
    homeMovementTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    homeMovementMaxRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 6,
      marginBottom: 6,
    },
    homeMovementMaxLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    homeMovementMaxValue: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    homeMovementRecentLine: {
      fontSize: 13,
      color: theme.textSecondary,
      lineHeight: 18,
    },
    homeMuscleBubbleOverlay: {
      flex: 1,
    },
    homeMuscleBubbleBackdropPress: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'transparent',
    },
    homeMuscleBubble: {
      position: 'absolute',
      borderRadius: 22,
      borderWidth: 1,
      overflow: 'visible',
      alignItems: 'center',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 18,
      elevation: 12,
    },
    homeMuscleBubbleGlass: {
      alignSelf: 'stretch',
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: theme.homeGlassBubble,
    },
    homeMuscleBubbleInner: {
      paddingHorizontal: 18,
      paddingTop: 16,
      paddingBottom: 14,
    },
    homeMuscleBubbleScroll: {
      maxHeight: 280,
    },
    homeMuscleBubbleTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.textPrimary,
      letterSpacing: -0.2,
    },
    homeMuscleBubbleSubtitle: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textMuted,
      marginTop: 2,
      marginBottom: 12,
      letterSpacing: 0.2,
    },
    homeMuscleBubbleEmpty: {
      fontSize: 14,
      color: theme.textSecondary,
      lineHeight: 20,
    },
    homeMuscleBubbleWorkoutBlock: {
      marginBottom: 14,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderFaint,
    },
    homeMuscleBubbleWorkoutBlockLast: {
      marginBottom: 0,
      paddingBottom: 0,
      borderBottomWidth: 0,
    },
    homeMuscleBubbleWorkoutLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textPrimary,
      marginBottom: 6,
    },
    homeMuscleBubbleWorkoutMeta: {
      fontSize: 13,
      color: theme.textSecondary,
      lineHeight: 18,
      marginBottom: 4,
    },
    homeMuscleBubbleMovementTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textPrimary,
      marginTop: 8,
      marginBottom: 2,
    },
    homeMuscleBubbleSetLine: {
      fontSize: 12,
      color: theme.textMuted,
      lineHeight: 17,
    },
    homeMuscleBubbleTail: {
      position: 'absolute',
      top: -7,
      width: 16,
      height: 16,
      borderLeftWidth: 1,
      borderTopWidth: 1,
      transform: [{ rotate: '45deg' }],
    },
    homeEmptyMovements: {
      padding: 24,
      alignItems: 'center',
    },
    homeEmptyMovementsText: {
      fontSize: 14,
      color: theme.textMuted,
      textAlign: 'center',
    },
  };
}

export default createHomeDashboardStyles(GAME_THEME_DARK);
