import { StyleSheet } from 'react-native';
import { GAME_THEME_DARK } from '../theme/gameTheme';

/** @param {typeof GAME_THEME_DARK} theme */
export function createHomeDashboardStyles(theme) {
  return {
    homeScreenScrollWrap: {
      flex: 1,
      backgroundColor: theme.screenBg,
      overflow: 'hidden',
    },
    homeScreenScroll: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    homeScreenContent: {
      overflow: 'visible',
    },
    homeScreenContentGrow: {
      flexGrow: 1,
    },
    homeProfileHeaderBar: {
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 10,
    },
    homeTopHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      position: 'relative',
    },
    homeTopHeaderLeft: {
      flex: 1,
      alignItems: 'flex-start',
      gap: 10,
      paddingRight: 12,
    },
    homeSessionTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.textPrimary,
      letterSpacing: -0.3,
    },
    homeTopDateCol: {
      alignItems: 'flex-end',
    },
    homeTopDateWeekday: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.5,
      color: theme.textMuted,
    },
    homeTopDateNumber: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.textPrimary,
      marginTop: -2,
    },
    homeTopBackToTodayButton: {
      position: 'absolute',
      right: 0,
      // Profile button (36) + column gap (10) aligns with session title row.
      top: 46,
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
    },
    homeTopBackToTodayButtonHidden: {
      opacity: 0,
    },
    homeTopBackToTodayText: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 26,
      marginTop: -1,
      color: theme.navAccent,
    },
    homeGamifiedSection: {
      position: 'relative',
      zIndex: 0,
      paddingHorizontal: 16,
      paddingTop: 58,
      paddingBottom: 28,
      backgroundColor: 'transparent',
      overflow: 'visible',
    },
    homeBodyPanelWrap: {
      flexGrow: 1,
      position: 'relative',
      zIndex: 2,
      overflow: 'visible',
      backgroundColor: 'transparent',
    },
    homeBodyPanelGlow: {
      position: 'absolute',
      top: -148,
      left: 0,
      right: 0,
      height: 280,
      zIndex: 0,
    },
    homeBodyPanelOverscrollCover: {
      position: 'absolute',
      top: -160,
      left: 0,
      right: 0,
      height: 220,
      backgroundColor: theme.screenBg,
      zIndex: 1,
    },
    homeBodyPanel: {
      flexGrow: 1,
      position: 'relative',
      zIndex: 1,
      paddingTop: 28,
      paddingHorizontal: 16,
      backgroundColor: theme.homeBodyPanelBg,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      borderWidth: 1,
      borderBottomWidth: 0,
      borderColor: theme.borderSubtle,
      gap: 18,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 8,
    },
    homeDateStripWrap: {
      width: '100%',
      marginHorizontal: -8,
    },
    homeDateStripList: {
      paddingHorizontal: 8,
    },
    homeDateCell: {
      width: 56,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
    },
    homeDateCellInner: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 48,
      minHeight: 72,
      borderRadius: 20,
      overflow: 'hidden',
      paddingVertical: 8,
    },
    homeDateCellGlass: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.homeGlassBubbleBorder,
      backgroundColor: theme.homeGlassBubble,
    },
    homeDateWeekday: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.6,
      color: theme.textMuted,
      marginBottom: 4,
    },
    homeDateWeekdaySelected: {
      color: theme.textPrimary,
    },
    homeDateNumber: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.textSecondary,
    },
    homeDateNumberSelected: {
      color: theme.textPrimary,
    },
    homeDateDot: {
      width: 5,
      height: 5,
      borderRadius: 3,
      marginTop: 6,
      backgroundColor: 'transparent',
    },
    homeDateDotLogged: {
      backgroundColor: theme.textPrimary,
    },
    homeLevelSelectWrap: {
      width: '100%',
      alignItems: 'center',
      minHeight: 120,
      flexDirection: 'column',
      paddingTop: 16,
      paddingBottom: 8,
      overflow: 'visible',
    },
    homeLevelSelectIconTrack: {
      paddingBottom: 0,
      overflow: 'visible',
    },
    homeLevelCircleCell: {
      width: 104,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 98,
      paddingVertical: 6,
      overflow: 'visible',
    },
    homeLevelSelectedRing: {
      position: 'absolute',
      zIndex: 0,
    },
    homeLevelSelectedRingIcon: {
      width: 86,
      height: 86,
      borderRadius: 43,
      top: 6,
      left: 6,
    },
    homeLevelSelectedRingRest: {
      width: 62,
      height: 62,
      borderRadius: 31,
      top: 5,
      left: 5,
    },
    homeLevelDayDateOverlay: {
      position: 'absolute',
      top: 18,
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 3,
    },
    homeLevelDayDateOverlayRest: {
      position: 'relative',
      top: 0,
    },
    homeLevelDayWeekdayRest: {
      fontSize: 6,
      color: 'rgba(255, 255, 255, 0.55)',
    },
    homeLevelDayNumberRest: {
      fontSize: 11,
      color: 'rgba(255, 255, 255, 0.7)',
    },
    homeLevelDayWeekday: {
      fontSize: 8,
      fontWeight: '700',
      letterSpacing: 0.4,
      color: '#FFFFFF',
      opacity: 0.92,
    },
    homeLevelDayNumber: {
      fontSize: 16,
      fontWeight: '800',
      color: '#FFFFFF',
      marginTop: -1,
      opacity: 0.95,
    },
    homeLevelRestWrap: {
      width: 72,
      height: 72,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'visible',
    },
    homeLevelTodayStarWrap: {
      position: 'absolute',
      top: 16,
      left: 0,
      right: 0,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 3,
    },
    homeLevelTodayStarWrapRest: {
      position: 'relative',
      top: 0,
    },
    homeLevelTodayStar: {
      fontSize: 28,
      lineHeight: 30,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    homeLevelTodayStarRest: {
      fontSize: 18,
      lineHeight: 20,
      color: 'rgba(255, 255, 255, 0.75)',
    },
    homeLevelCircleRest: {
      width: 50,
      height: 50,
      borderRadius: 25,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(75, 85, 99, 0.32)',
    },
    homeLevelCircleSmall: {
      width: 84,
      height: 84,
      borderRadius: 42,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.homeGamifiedInactive,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.38,
      shadowRadius: 6,
      elevation: 6,
    },
    homeLevelCircleSmallBottom: {
      position: 'absolute',
      bottom: -5,
      left: 8,
      right: 8,
      height: 12,
      borderRadius: 6,
      backgroundColor: 'rgba(0,0,0,0.28)',
    },
    homeLevelCircleLarge: {
      width: 88,
      height: 88,
      borderRadius: 44,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 6,
      elevation: 6,
    },
    homeLevelCircleLargeBottom: {
      position: 'absolute',
      bottom: -4,
      left: 8,
      right: 8,
      height: 12,
      borderRadius: 6,
      backgroundColor: 'rgba(0,0,0,0.3)',
    },
    homeLevelStar: {
      fontSize: 32,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    homeLevelIconShell: {
      width: 98,
      height: 98,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'visible',
    },
    homeLevelIconWrap: {
      width: 72,
      height: 72,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 36,
      position: 'relative',
      overflow: 'visible',
    },
    homeLevelIconImage: {
      width: 72,
      height: 72,
    },
    homeLevelIconMuted: {
      opacity: 0.42,
    },
    homeLevelStarSmall: {
      fontSize: 34,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    homeLevelStarMuted: {
      opacity: 0.72,
    },
    homeLevelRestIcon: {
      fontSize: 22,
      color: 'rgba(255,255,255,0.7)',
    },
    homeLevelRestIconSmall: {
      fontSize: 18,
      color: 'rgba(255,255,255,0.32)',
      fontWeight: '500',
    },
    homeStatsBar: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      backgroundColor: theme.homeStatBarBg,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
    },
    homeStatCell: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    homeStatCellTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    homeStatIconWell: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.iconWellBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeStatIcon: {
      width: 16,
      height: 16,
      tintColor: theme.navAccent,
      resizeMode: 'contain',
    },
    homeStatCheckMark: {
      fontSize: 15,
      fontWeight: '800',
      color: theme.navAccent,
      lineHeight: 16,
    },
    homeStatValue: {
      fontSize: 20,
      fontWeight: '800',
      fontStyle: 'italic',
      color: theme.textPrimary,
      letterSpacing: -0.5,
    },
    homeStatLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textMuted,
      textAlign: 'center',
      letterSpacing: 0.15,
    },
    homeCarouselWrap: {
      borderRadius: 16,
      backgroundColor: theme.homeCarouselBg,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      overflow: 'hidden',
    },
    homeCarouselPage: {
      width: '100%',
      minHeight: 88,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    homeCarouselTextCol: {
      flex: 1,
    },
    homeCarouselValue: {
      fontSize: 28,
      fontWeight: '800',
      color: theme.textPrimary,
      letterSpacing: -0.5,
    },
    homeCarouselLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: theme.textMuted,
      marginTop: 2,
    },
    homeCarouselBadge: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.streakGold,
    },
    homeCarouselBadgeImage: {
      width: 36,
      height: 36,
      resizeMode: 'contain',
    },
    homeCarouselRankImage: {
      width: 52,
      height: 52,
      resizeMode: 'contain',
    },
    homeCarouselDots: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 6,
      paddingTop: 8,
      paddingBottom: 10,
    },
    homeMovementSection: {
      gap: 10,
    },
    planScreenTitleSection: {
      width: '100%',
      alignSelf: 'stretch',
      marginHorizontal: -22,
      marginTop: 8,
      marginBottom: 8,
      minHeight: 44,
      justifyContent: 'center',
      overflow: 'visible',
    },
    planScreenTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    planScreenTitleBar: {
      position: 'absolute',
      top: '50%',
      height: 20,
      marginTop: 0,
      backgroundColor: theme.navAccent,
    },
    planScreenTitle: {
      color: theme.textPrimary,
      fontSize: 32,
      fontWeight: '700',
      fontStyle: 'italic',
      marginLeft: 22,
      zIndex: 1,
    },
    planScreenTitleIcon: {
      width: 28,
      height: 28,
      marginTop: -2,
    },
    planScreenSubtitle: {
      color: theme.navAccent,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 14,
      alignSelf: 'flex-start',
      width: '100%',
      maxWidth: 420,
      letterSpacing: 0.3,
      textTransform: 'lowercase',
    },
    planWeekdayShell: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 18,
      width: '100%',
      maxWidth: 420,
      alignSelf: 'center',
    },
    planWeekdayBar: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.28)',
      backgroundColor: theme.homeStatBarBg,
      paddingHorizontal: 8,
      paddingVertical: 12,
    },
    planWeekdayBarHero: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
    },
    planWeekdayHeroHidden: {
      opacity: 0,
    },
    planWeekdayCell: {
      alignItems: 'center',
      gap: 8,
      minWidth: 32,
    },
    planWeekdayLetter: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    planWeekdayLetterSelected: {
      color: theme.navAccent,
      fontWeight: '800',
    },
    planWeekdayCircleWrap: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
    },
    planWeekdayDotStack: {
      alignItems: 'center',
    },
    planWeekdayUnderline: {
      width: 26,
      height: 3,
      borderRadius: 2,
      backgroundColor: theme.navAccent,
      marginTop: 6,
    },
    planWeekdayCircle: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
    },
    planEditButton: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      paddingHorizontal: 10,
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    planEditButtonIcon: {
      width: 18,
      height: 18,
      tintColor: '#FFFFFF',
    },
    planEditButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    planWorkoutHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
      marginBottom: 12,
      width: '100%',
      maxWidth: 420,
      alignSelf: 'center',
    },
    planWorkoutHeaderText: {
      flex: 1,
      gap: 2,
      minWidth: 0,
      paddingRight: 4,
    },
    planWorkoutTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 0,
      minHeight: 28,
    },
    planWorkoutTitleMarqueeWrap: {
      flex: 1,
      minWidth: 0,
      height: 22,
      position: 'relative',
    },
    planWorkoutTitleMarquee: {
      flex: 1,
      minWidth: 0,
      height: 22,
      overflow: 'hidden',
      justifyContent: 'center',
    },
    planWorkoutTitleMarqueeTrack: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'nowrap',
    },
    planWorkoutTitleMeasureHost: {
      position: 'absolute',
      opacity: 0,
      left: 0,
      top: 0,
      width: 2000,
    },
    planWorkoutTitle: {
      fontSize: 18,
      fontWeight: '800',
      lineHeight: 22,
      color: theme.textPrimary,
    },
    planWorkoutTitleLabel: {
      flexShrink: 0,
      flexGrow: 0,
    },
    planWorkoutMoreButton: {
      width: 34,
      height: 28,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    // Same footprint as the "..." pill so the title does not shift when editing starts.
    planWorkoutMoreButtonPlaceholder: {
      width: 34,
      height: 28,
      flexShrink: 0,
    },
    planWorkoutMoreDots: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
    },
    planWorkoutMoreDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
    },
    planWorkoutPillCancelMark: {
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 18,
      color: '#FFFFFF',
      marginTop: -1,
    },
    planWorkoutSubtitle: {
      fontSize: 13,
      lineHeight: 17,
      color: theme.textMuted,
    },
    planWorkoutExerciseCount: {
      fontSize: 12,
      lineHeight: 16,
      color: theme.textMuted,
    },
    planWorkoutHeaderActions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 6,
      flexShrink: 0,
      minHeight: 38,
    },
    planWorkoutPillButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      paddingHorizontal: 10,
      paddingVertical: 8,
      minHeight: 38,
    },
    planWorkoutPillIcon: {
      width: 16,
      height: 16,
      tintColor: '#FFFFFF',
    },
    planWorkoutPillPlus: {
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 18,
      color: '#FFFFFF',
      marginTop: -1,
    },
    planWorkoutPillLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    planWorkoutEditButton: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      paddingHorizontal: 10,
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    planWorkoutEditIcon: {
      width: 18,
      height: 18,
    },
    planChangeButton: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    planChangeButtonDisabled: {
      backgroundColor: theme.chipWellBg,
      borderColor: theme.borderSubtle,
      opacity: 0.55,
    },
    planChangeButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    planEmptyCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.22)',
      backgroundColor: theme.homeCarouselBg,
      padding: 16,
      gap: 8,
      width: '100%',
      maxWidth: 420,
      alignSelf: 'center',
      borderLeftWidth: 3,
      borderLeftColor: theme.navAccent,
    },
    planEmptyEmbedded: {
      paddingVertical: 4,
      gap: 8,
      width: '100%',
    },
    planEmptyTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    planEmptyBody: {
      fontSize: 14,
      lineHeight: 20,
      color: theme.textMuted,
    },
    planInlineLinkButton: {
      alignSelf: 'flex-start',
      borderBottomWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.45)',
      paddingBottom: 2,
      marginTop: 2,
      marginBottom: 10,
    },
    planInlineLinkText: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.navAccent,
    },
    planPickerModalCard: {
      width: '88%',
      maxWidth: 420,
    },
    planOptionsModalCard: {
      width: '88%',
      maxWidth: 420,
      borderRadius: 18,
      borderWidth: 1,
      padding: 16,
      zIndex: 2,
      elevation: 12,
    },
    planOptionsSecondaryButton: {
      marginTop: 8,
      borderRadius: 12,
      borderWidth: 1,
      paddingVertical: 14,
      paddingHorizontal: 16,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
    },
    planOptionsSecondaryButtonText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    planOptionsPrimaryButton: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 16,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
    },
    planOptionsPrimaryButtonText: {
      fontSize: 16,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    planOptionsRowActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 16,
    },
    planPickerScroll: {
      maxHeight: 280,
    },
    planPickerOption: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.homeCarouselBg,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
    },
    planPickerOptionSelected: {
      backgroundColor: 'rgba(255, 43, 58, 0.14)',
      borderColor: theme.navAccent,
    },
    planPickerOptionTitle: {
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 3,
      color: theme.textPrimary,
    },
    planPickerOptionTitleSelected: {
      color: theme.textPrimary,
    },
    planPickerOptionMeta: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textMuted,
    },
    planPickerOptionMetaSelected: {
      color: theme.textSecondary,
    },
    planSwapPanelRow: {
      flexDirection: 'row',
      gap: 14,
      paddingHorizontal: 16,
      paddingBottom: 18,
    },
    planLibraryActionsWrap: {
      width: '100%',
      maxWidth: 420,
      alignSelf: 'center',
      paddingTop: 4,
      paddingBottom: 10,
    },
    planLibraryActionsPanel: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.cardBg,
      padding: 10,
    },
    planLibraryActionsRow: {
      flexDirection: 'row',
      gap: 10,
    },
    planLibraryActionButton: {
      flex: 1,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.surfaceRaised,
      paddingVertical: 14,
      paddingHorizontal: 14,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
    },
    planSwapPanelButton: {
      flex: 1,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.homeCarouselBg,
      paddingVertical: 16,
      paddingHorizontal: 16,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
    },
    planSwapPanelIcon: {
      width: 30,
      height: 30,
      marginBottom: 10,
      tintColor: theme.navAccent,
    },
    planSwapPanelPlusWrap: {
      width: 30,
      height: 30,
      marginBottom: 10,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    planSwapPanelPlusText: {
      fontSize: 48,
      fontWeight: '400',
      lineHeight: 48,
      color: theme.navAccent,
      textAlign: 'center',
      includeFontPadding: false,
      marginTop: -4,
    },
    planSwapPanelLabel: {
      fontSize: 16,
      fontWeight: '800',
      textAlign: 'left',
      color: theme.textPrimary,
      lineHeight: 20,
    },
    planSwapBackTouch: {
      paddingHorizontal: 4,
      paddingVertical: 4,
      marginRight: 4,
      marginTop: -2,
    },
    planSwapBackMark: {
      fontSize: 28,
      fontWeight: '500',
      lineHeight: 30,
    },
    planSwapSavedCard: {
      flex: 1,
      borderTopWidth: StyleSheet.hairlineWidth,
      marginTop: 2,
    },
    planSwapSectionLabel: {
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      marginBottom: 8,
      marginTop: 4,
      color: theme.textMuted,
    },
    planSwapSplitRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.homeCarouselBg,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 8,
      gap: 10,
    },
    planSwapSplitRowCurrent: {
      backgroundColor: 'rgba(255, 43, 58, 0.14)',
      borderColor: theme.navAccent,
    },
    planSwapSplitRowDay: {
      fontSize: 14,
      fontWeight: '800',
      minWidth: 72,
      color: theme.textPrimary,
    },
    planSwapSplitRowBody: {
      flex: 1,
      minWidth: 0,
    },
    planSwapSplitRowTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    planSwapSplitRowMeta: {
      fontSize: 12,
      fontWeight: '600',
      marginTop: 2,
      color: theme.textMuted,
    },
    planSwapCurrentBadge: {
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.navAccent,
      backgroundColor: 'rgba(255, 43, 58, 0.12)',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    planSwapCurrentBadgeText: {
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      color: theme.navAccent,
    },
    planContentWrap: {
      width: '100%',
      maxWidth: 420,
      alignSelf: 'center',
    },
    planContentWrapFlex: {
      flex: 1,
      minHeight: 0,
    },
    planScreenScroll: {
      flex: 1,
      width: '100%',
    },
    planScreenScrollContent: {
      alignItems: 'stretch',
      flexGrow: 1,
    },
    planDaySection: {
      width: '100%',
      paddingTop: 6,
      paddingBottom: 8,
      gap: 4,
    },
    planExerciseSummaryList: {
      gap: 8,
      width: '100%',
      marginTop: 8,
    },
    planExerciseSummaryRow: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.cardBg,
      paddingVertical: 12,
      paddingHorizontal: 14,
      gap: 4,
    },
    planExerciseSummaryName: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    planExerciseSummaryMeta: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textMuted,
    },
    planDayBuilderRoot: {
      width: '100%',
      gap: 14,
      marginTop: 8,
    },
    planDayBuilderList: {
      width: '100%',
      gap: 10,
    },
    planDayBuilderActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginTop: 4,
    },
    planDayBuilderCancelButton: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.surfaceRaised,
      paddingVertical: 16,
      paddingHorizontal: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    planDayBuilderCancelText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    planDayBuilderSaveButtonFlex: {
      flex: 1,
    },
    planDayCard: {
      flex: 1,
      width: '100%',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.homeBodyPanelBg,
      overflow: 'hidden',
      minHeight: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.16,
      shadowRadius: 10,
      elevation: 6,
    },
    planDayPager: {
      flex: 1,
    },
    planDayPagerContent: {
      flexGrow: 1,
    },
    planDayPagerPage: {
      flex: 1,
      overflow: 'hidden',
    },
    planDayPagerPageContent: {
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 22,
      gap: 4,
      flexGrow: 1,
    },
    planSwapCreateCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.homeCarouselBg,
      paddingHorizontal: 16,
      paddingVertical: 18,
      marginTop: 4,
      alignItems: 'center',
    },
    planSwapCreateTitle: {
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 6,
      textAlign: 'center',
    },
    planSwapCreateBody: {
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
      marginBottom: 14,
    },
    planSwapCreateButton: {
      borderRadius: 12,
      borderWidth: 1,
      paddingHorizontal: 18,
      paddingVertical: 12,
    },
    planSwapCreateButtonText: {
      fontSize: 15,
      fontWeight: '800',
    },
    planTimelineScreen: {
      flex: 1,
      backgroundColor: theme.screenBg,
    },
    planTimelineBody: {
      flex: 1,
      position: 'relative',
    },
    planTimelineHeaderOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 3,
      paddingHorizontal: 16,
      paddingTop: 14,
      alignItems: 'flex-end',
      justifyContent: 'flex-start',
    },
    planTimelineTopFade: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 2,
    },
    planTimelineBottomFade: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      zIndex: 2,
    },
    planTimelineBackButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
    },
    planTimelineBackMark: {
      fontSize: 34,
      fontWeight: '400',
      lineHeight: 38,
      color: theme.textPrimary,
      paddingHorizontal: 8,
    },
    planTimelineScroll: {
      flex: 1,
    },
    planTimelineScrollContent: {
      paddingHorizontal: 0,
      paddingBottom: 40,
      alignItems: 'stretch',
    },
    planTimelineEmpty: {
      color: theme.textMuted,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 12,
      maxWidth: 420,
      alignSelf: 'center',
      width: '100%',
    },
    planTimelineList: {
      width: '100%',
      maxWidth: 420,
      alignSelf: 'center',
      marginTop: 8,
    },
    planTimelineRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
      minHeight: 148,
      marginBottom: 14,
    },
    planTimelineRail: {
      width: 64,
      alignItems: 'center',
      position: 'relative',
      paddingTop: 18,
    },
    // Solid connector centered on the dots: from bottom of this day-dot to top of the next.
    // top = rail paddingTop (18) + wrap inset (4) + dayDot (48) = 70
    // bottom reaches through row gap (14) + next paddingTop (18) + next wrap inset (4) = -36
    planTimelineConnector: {
      position: 'absolute',
      top: 70,
      bottom: -36,
      width: 2,
      left: 31,
      borderRadius: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.35)',
      zIndex: 0,
    },
    planTimelineIconWrap: {
      width: 56,
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
    },
    planTimelineDayDot: {
      width: 48,
      height: 48,
      borderRadius: 24,
      borderWidth: 2,
    },
    planTimelineDayDotSource: {
      opacity: 0.35,
    },
    planTimelineDayDotDropTarget: {
      transform: [{ scale: 1.12 }],
      borderRadius: 28,
      borderWidth: 2,
      borderColor: 'rgba(255, 255, 255, 0.55)',
      padding: 2,
    },
    planTimelineDragGhost: {
      position: 'absolute',
      width: 48,
      height: 48,
      borderRadius: 24,
      borderWidth: 2,
      zIndex: 40,
      elevation: 8,
      shadowColor: '#000',
      shadowOpacity: 0.35,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
    },
    planTimelineIconImage: {
      width: 56,
      height: 56,
    },
    planTimelineIconFallback: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.homeGamifiedInactive,
    },
    planTimelineRestCircle: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: 'rgba(75, 85, 99, 0.32)',
      borderWidth: 2,
      borderColor: 'rgba(255, 255, 255, 0.28)',
    },
    planTimelineLetter: {
      position: 'absolute',
      fontSize: 18,
      fontWeight: '800',
      color: '#FFFFFF',
      textShadowColor: 'rgba(0, 0, 0, 0.45)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    planTimelineCardSlot: {
      flex: 1,
      paddingLeft: 8,
    },
    planTimelineCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.homeCarouselBg,
      paddingHorizontal: 14,
      paddingTop: 12,
      paddingBottom: 14,
      minHeight: 140,
    },
    planTimelineCardRest: {
      opacity: 0.78,
    },
    planTimelineCardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 12,
    },
    planTimelineCardHeaderText: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    planTimelineCardTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    planTimelineCardMeta: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textMuted,
      textTransform: 'lowercase',
    },
    planTimelineMoreButton: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      marginTop: -4,
    },
    planTimelineMoreButtonText: {
      fontSize: 28,
      fontWeight: '700',
      lineHeight: 30,
      color: theme.textPrimary,
    },
    planTimelineSwapButton: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.35)',
      backgroundColor: 'rgba(255, 43, 58, 0.16)',
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    planTimelineSwapButtonText: {
      fontSize: 13,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    planTimelineCardBody: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    planTimelineMuscleWell: {
      width: 88,
      height: 88,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.chipWellBg,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      paddingHorizontal: 4,
    },
    planTimelineMuscleDiagrams: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
    },
    planTimelineMuscleHalf: {
      width: 36,
    },
    planTimelineMusclePlaceholder: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textMuted,
      textAlign: 'center',
      lineHeight: 14,
      textTransform: 'lowercase',
    },
    planTimelineStats: {
      flex: 1,
      gap: 6,
      justifyContent: 'center',
    },
    planTimelineStatLine: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    planTimelineStatLineMuted: {
      color: theme.textMuted,
    },
    planBuilderHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingBottom: 10,
      gap: 8,
    },
    planBuilderTitle: {
      flex: 1,
      fontSize: 20,
      fontWeight: '800',
      color: theme.textPrimary,
      textAlign: 'center',
      paddingRight: 36,
    },
    planBuilderBackTouch: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    planBuilderBackMark: {
      fontSize: 32,
      fontWeight: '500',
      lineHeight: 34,
      color: theme.textPrimary,
    },
    planBuilderBottomBar: {
      paddingHorizontal: 16,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme.borderSubtle,
      backgroundColor: theme.screenBg,
    },
    planBuilderSaveButton: {
      borderRadius: 16,
      backgroundColor: theme.navAccent,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    planBuilderSaveButtonDisabled: {
      opacity: 0.38,
    },
    planBuilderSaveButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
    },
    planBuilderTargetHint: {
      marginTop: 4,
      marginBottom: 14,
      fontSize: 13,
      fontWeight: '600',
      color: theme.textMuted,
    },
    planBuilderTargetRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    planBuilderTargetField: {
      flex: 1,
      gap: 6,
    },
    planBuilderTargetLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textMuted,
    },
    planBuilderTargetInput: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.surfaceRaised,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 18,
      fontWeight: '700',
      color: theme.textPrimary,
      textAlign: 'center',
    },
    planBuilderNameInput: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(255, 43, 58, 0.25)',
      backgroundColor: theme.surfaceRaised,
      paddingHorizontal: 14,
      paddingVertical: 14,
      fontSize: 17,
      fontWeight: '700',
      color: theme.textPrimary,
      marginBottom: 16,
    },
    homeMovementSectionTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textSecondary,
      marginBottom: 2,
    },
    homeMovementCard: {
      backgroundColor: theme.cardBg,
      borderRadius: 14,
      padding: 14,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
    },
    homeMovementCardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 8,
    },
    homeMovementChipWell: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: theme.chipWellBg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.chipWellBorder,
    },
    homeMovementChipIcon: {
      width: 28,
      height: 28,
      resizeMode: 'contain',
    },
    homeMovementTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    homeMovementTextColumn: {
      flex: 1,
      gap: 4,
    },
    homeMovementTargetLine: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    homeMovementMaxRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 6,
      marginBottom: 6,
      flexShrink: 1,
    },
    homeMovementMaxLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    homeMovementMaxValue: {
      fontSize: 18,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    homeMovementRecentLine: {
      fontSize: 13,
      color: theme.textSecondary,
      lineHeight: 18,
    },
    homeMovementSparklineRow: {
      alignItems: 'stretch',
      marginTop: 2,
    },
    homeMovementSparklineWrap: {
      alignItems: 'flex-start',
      alignSelf: 'stretch',
    },
    homeMovementSparklinePlaceholder: {
      width: '100%',
      height: 72,
      borderRadius: 8,
      backgroundColor: 'rgba(0, 0, 0, 0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeMovementSparklinePlaceholderText: {
      fontSize: 10,
      fontWeight: '600',
      color: theme.textMuted,
      textTransform: 'lowercase',
    },
    homeMovementSparklineTrend: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textMuted,
      textAlign: 'left',
      marginTop: 6,
      textTransform: 'lowercase',
    },
    homeMovementSparklineTrendUp: {
      color: theme.navAccent,
    },
    homeMovementSparklineTrendDown: {
      color: theme.textSecondary,
    },
    homeMovementEmptyText: {
      fontSize: 13,
      color: theme.textMuted,
      lineHeight: 18,
    },
    homeMovementImagePlaceholder: {
      width: 56,
      minHeight: 72,
      borderRadius: 12,
      backgroundColor: theme.chipWellBg,
      borderWidth: 1,
      borderColor: theme.chipWellBorder,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
      paddingVertical: 8,
      gap: 4,
    },
    homeMovementPlaceholderIcon: {
      width: 26,
      height: 26,
      resizeMode: 'contain',
      opacity: 0.85,
    },
    homeMovementPlaceholderText: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textMuted,
      textAlign: 'center',
    },
    homeMuscleBubbleOverlay: {
      flex: 1,
    },
    homeMuscleBubbleBackdropPress: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'transparent',
    },
    homeMuscleBubble: {
      position: 'absolute',
      borderRadius: 22,
      borderWidth: 1,
      overflow: 'visible',
      alignItems: 'center',
    },
    homeMuscleBubbleGlass: {
      alignSelf: 'stretch',
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: theme.homeGlassBubble,
    },
    homeMuscleBubbleInner: {
      paddingHorizontal: 18,
      paddingTop: 16,
      paddingBottom: 14,
    },
    homeMuscleBubbleScroll: {
      maxHeight: 360,
    },
    homeMuscleBubbleTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme.textPrimary,
      letterSpacing: -0.2,
    },
    homeMuscleBubbleSubtitle: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textMuted,
      marginTop: 2,
      marginBottom: 12,
      letterSpacing: 0.2,
    },
    homeMuscleBubbleEmpty: {
      fontSize: 14,
      color: theme.textSecondary,
      lineHeight: 20,
    },
    homeLevelPlanPreviewRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      marginBottom: 12,
    },
    homeLevelPlanMuscleWell: {
      width: 96,
      height: 96,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.borderSubtle,
      backgroundColor: theme.chipWellBg,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      paddingHorizontal: 4,
    },
    homeLevelPlanMuscleDiagrams: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
    },
    homeLevelPlanMuscleHalf: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeLevelPlanMusclePlaceholder: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.textMuted,
      textAlign: 'center',
      lineHeight: 15,
    },
    homeLevelPlanStatsCol: {
      flex: 1,
      gap: 4,
      minWidth: 0,
    },
    homeLevelPlanStatLine: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    homeLevelPlanStatLineMuted: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textMuted,
      lineHeight: 16,
    },
    homeLevelPlanExerciseList: {
      gap: 6,
      marginBottom: 14,
    },
    homeLevelPlanExerciseRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    homeLevelPlanExerciseName: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    homeLevelPlanExerciseTarget: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.textMuted,
    },
    homeLevelPlanExerciseMore: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.textMuted,
      marginTop: 2,
    },
    homeLevelPlanStartButton: {
      borderRadius: 14,
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeLevelPlanStartButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    homeMuscleBubbleWorkoutBlock: {
      marginBottom: 14,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderFaint,
    },
    homeMuscleBubbleWorkoutBlockLast: {
      marginBottom: 0,
      paddingBottom: 0,
      borderBottomWidth: 0,
    },
    homeMuscleBubbleWorkoutLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textPrimary,
      marginBottom: 6,
    },
    homeMuscleBubbleWorkoutMeta: {
      fontSize: 13,
      color: theme.textSecondary,
      lineHeight: 18,
      marginBottom: 4,
    },
    homeMuscleBubbleMovementTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textPrimary,
      marginTop: 8,
      marginBottom: 2,
    },
    homeMuscleBubbleSetLine: {
      fontSize: 12,
      color: theme.textMuted,
      lineHeight: 17,
    },
    homeMuscleBubbleTail: {
      position: 'absolute',
      top: -7,
      width: 16,
      height: 16,
      borderLeftWidth: 1,
      borderTopWidth: 1,
      transform: [{ rotate: '45deg' }],
    },
    homeEmptyMovements: {
      padding: 24,
      alignItems: 'center',
    },
    homeEmptyMovementsText: {
      fontSize: 14,
      color: theme.textMuted,
      textAlign: 'center',
    },
  };
}

export default createHomeDashboardStyles(GAME_THEME_DARK);
