import { StyleSheet, Platform } from 'react-native';
import { MAIN_NAV_TRACK_HEIGHT } from '../constants/layout';

/** Home / More header bar (translucent over the charcoal menu body). */
const MENU_TOP_BAR_PURPLE = 'rgba(93, 85, 216, 0.6)';

/**
 * Opaque equivalent of MENU_TOP_BAR_PURPLE composited over #1A1A1C (menuBody).
 * The status-bar strip often sits over a darker native layer, so translucent purple
 * reads darker than the header bar; this solid matches the bar’s look on the body.
 */
const MENU_TOP_BAR_STATUS_MATCH = '#423D8D';

const menuLayoutProfileStyles = {
  mainTabsContentShell: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#1A1A1C',
  },
  mainTabsBottomFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 25,
  },
  mainTabsFloatingNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 30,
  },
  mainTabsFullBleedScroll: {
    flex: 1,
  },
  screenFadeContainer: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#111214',
  },
  menuSafeArea: {
    backgroundColor: '#EDEDED',
  },
  container: {
    padding: 20,
    paddingBottom: 32,
    alignItems: 'center',
  },
  workoutScreenWrapper: {
    flex: 1,
  },
  workoutScrollContent: {
    paddingTop: 44,
    paddingBottom: 140,
  },
  workoutSafeAreaLift: {
    paddingTop: 0,
  },
  workoutKeyboardAvoid: {
    flex: 1,
  },
  workoutGlowTop: {
    opacity: 0.55,
  },
  workoutGlowBottom: {
    opacity: 0.7,
  },
  workoutNotepadTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 8,
  },
  workoutHelpIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(75, 60, 193, 0.35)',
  },
  workoutHelpIconText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#4B3CC1',
  },
  workoutWideButton: {
    marginTop: 4,
    marginBottom: 10,
  },
  workoutEndButton: {
    width: '100%',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 8,
  },
  workoutHelpModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  workoutHelpModalCard: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
  workoutHelpModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 12,
  },
  workoutHelpModalClose: {
    marginTop: 14,
    paddingVertical: 14,
    marginBottom: 0,
  },
  workoutCloseButtonMenu: {
    position: 'absolute',
    top: 4,
    left: 8,
    zIndex: 20,
    width: 44,
    height: 44,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  /** Workout screen: open targets + muscle map sheet (top right). */
  workoutTargetsTopButton: {
    position: 'absolute',
    top: 4,
    right: 8,
    zIndex: 20,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 44,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  workoutTargetsTopButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4B3CC1',
  },
  menuScreen: {
    flex: 1,
    backgroundColor: '#1A1A1C',
  },
  menuScreenWithHeaderSafeArea: {
    flex: 1,
    // Solid tint matches translucent menuTopBar over #1A1A1C (see MENU_TOP_BAR_STATUS_MATCH).
    backgroundColor: MENU_TOP_BAR_STATUS_MATCH,
  },
  menuBody: {
    flex: 1,
    backgroundColor: '#1A1A1C',
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 8,
  },
  menuTopBar: {
    width: 'auto',
    marginLeft: -22,
    marginRight: -22,
    marginTop: -14,
    minHeight: 78,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: MENU_TOP_BAR_PURPLE,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderTopWidth: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  menuRankProgressBlock: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  menuRankProgressTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    overflow: 'hidden',
  },
  menuRankProgressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: '#5D55D8',
    minWidth: 4,
  },
  menuRankProgressHint: {
    marginTop: 4,
    color: 'rgba(238, 241, 255, 0.78)',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  menuRankBadgeWrap: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuRankBadge: {
    width: 44,
    height: 44,
  },
  streakRankPanel: {
    width: '100%',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: 'rgba(93, 85, 216, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
  },
  streakRankPanelTitle: {
    color: '#EEF1FF',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 6,
  },
  streakRankPanelIntro: {
    color: 'rgba(238, 241, 255, 0.88)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  streakRankCurrentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  streakRankCurrentBadge: {
    width: 64,
    height: 64,
    marginRight: 12,
  },
  streakRankCurrentTextCol: {
    flex: 1,
    minWidth: 0,
  },
  streakRankCurrentLabel: {
    color: '#EEF1FF',
    fontSize: 20,
    fontWeight: '800',
  },
  streakRankCurrentSub: {
    color: 'rgba(238, 241, 255, 0.75)',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 2,
    marginBottom: 8,
  },
  streakRankProgressTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    overflow: 'hidden',
    marginBottom: 6,
  },
  streakRankProgressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: '#5D55D8',
    minWidth: 4,
  },
  streakRankProgressHint: {
    color: 'rgba(238, 241, 255, 0.78)',
    fontSize: 13,
    fontWeight: '600',
  },
  streakRankLadderHeading: {
    color: 'rgba(238, 241, 255, 0.9)',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  streakRankLadderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: 'rgba(28, 30, 36, 0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  streakRankLadderRowEarned: {
    borderColor: 'rgba(255, 255, 255, 0.16)',
  },
  streakRankLadderRowCurrent: {
    borderColor: 'rgba(93, 85, 216, 0.85)',
    backgroundColor: 'rgba(44, 36, 138, 0.45)',
  },
  streakRankLadderIcon: {
    width: 36,
    height: 36,
    marginRight: 10,
  },
  streakRankLadderIconLocked: {
    opacity: 0.35,
  },
  streakRankLadderTextCol: {
    flex: 1,
    minWidth: 0,
  },
  streakRankLadderName: {
    color: '#EEF1FF',
    fontSize: 15,
    fontWeight: '700',
  },
  streakRankLadderNameLocked: {
    color: 'rgba(238, 241, 255, 0.55)',
  },
  streakRankLadderWeeks: {
    color: 'rgba(238, 241, 255, 0.65)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 1,
  },
  streakRankLadderCheck: {
    color: '#4ADE80',
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 8,
  },
  menuTopBarDateText: {
    color: '#EEF1FF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  menuMoreTopBarSpacer: {
    width: 52,
    height: 52,
  },
  /** More tab: flat dark gray (no purple glow / glass rows). */
  menuMoreScreen: {
    flex: 1,
    backgroundColor: '#1A1A1C',
  },
  menuMoreHeader: {
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 12,
  },
  menuMoreHeaderTitle: {
    color: '#EEF1FF',
    fontSize: 28,
    fontWeight: '700',
  },
  menuMoreScroll: {
    flex: 1,
  },
  menuMoreScrollContent: {
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 24,
  },
  menuMoreLinkGroup: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#26292F',
  },
  menuMoreSectionTitle: {
    color: '#EEF1FF',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
  },
  menuMoreBodyText: {
    color: 'rgba(238, 241, 255, 0.88)',
    fontSize: 15,
    lineHeight: 22,
  },
  menuMoreIntro: {
    color: 'rgba(238, 241, 255, 0.82)',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 6,
  },
  menuMoreSectionHeading: {
    color: 'rgba(238, 241, 255, 0.5)',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    marginTop: 24,
    marginBottom: 8,
  },
  menuMoreSectionHeadingFirst: {
    marginTop: 0,
  },
  menuMoreLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    backgroundColor: '#26292F',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 0,
    borderRadius: 0,
    borderWidth: 0,
  },
  menuMoreLinkRowSeparator: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
  },
  menuMoreLinkRowMuted: {
    opacity: 0.65,
  },
  menuMoreLinkIconWell: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#353840',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  menuMoreLinkIcon: {
    width: 28,
    height: 28,
  },
  menuMoreLinkTextBlock: {
    flex: 1,
    paddingRight: 12,
    minWidth: 0,
  },
  menuMoreLinkTitle: {
    color: '#EEF1FF',
    fontSize: 17,
    fontWeight: '600',
  },
  menuMoreLinkSubtitle: {
    color: 'rgba(238, 241, 255, 0.72)',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  menuMoreLinkChevron: {
    color: 'rgba(238, 241, 255, 0.45)',
    fontSize: 26,
    fontWeight: '300',
    marginTop: -2,
  },
  menuSubscreenNavTitle: {
    color: '#EEF1FF',
    fontSize: 22,
    fontWeight: '800',
    alignSelf: 'center',
  },
  menuMoreEmphasisInline: {
    color: '#F59E0B',
    fontWeight: '800',
  },
  menuMoreWeekdayBarInCard: {
    marginTop: 16,
  },
  // Shell only: no dark tray behind the bar — just spacing + the light pill row + FAB.
  menuBottomNav: {
    width: 'auto',
    marginLeft: -22,
    marginRight: -22,
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingTop: 12,
    position: 'relative',
    backgroundColor: 'transparent',
    overflow: 'visible',
  },
  menuBottomNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '96%',
    maxWidth: 420,
    position: 'relative',
    zIndex: 1,
  },
  menuNavFabWrap: {
    zIndex: 2,
    marginLeft: -26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuNavFab: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(248, 248, 255, 0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.5)',
    boxShadow: '0px 6px 20px rgba(0, 0, 0, 0.25)',
  },
  menuNavFabPlus: {
    fontSize: 42,
    lineHeight: 46,
    color: '#4B3CC1',
    fontWeight: '300',
    marginTop: -2,
  },
  menuNavTrack: {
    flex: 1,
    flexGrow: 1,
    minHeight: MAIN_NAV_TRACK_HEIGHT,
    height: MAIN_NAV_TRACK_HEIGHT,
    position: 'relative',
    backgroundColor: 'transparent',
    borderTopLeftRadius: 26,
    borderBottomLeftRadius: 26,
    borderTopRightRadius: 26,
    borderBottomRightRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    overflow: 'hidden',
  },
  menuNavTrackBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  menuNavTrackScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  menuNavTrackInner: {
    flex: 1,
    justifyContent: 'center',
    minHeight: MAIN_NAV_TRACK_HEIGHT,
    paddingLeft: 8,
    paddingRight: 34,
    position: 'relative',
    zIndex: 1,
    backgroundColor: 'transparent',
  },
  menuNavTabsRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    zIndex: 1,
  },
  menuNavTabTouchable: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  menuNavSlotAnchor: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  menuNavTabIndicator: {
    position: 'absolute',
    left: 0,
    borderRadius: 18,
    overflow: 'hidden',
    zIndex: 0,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.42)',
    backgroundColor: 'transparent',
    boxShadow: '0px 2px 12px rgba(0, 0, 0, 0.14)',
  },
  menuNavTabIndicatorBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  /** Stronger frost than the tab strip scrim so the active tab reads as a denser glass pill. */
  menuNavTabIndicatorScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.46)',
  },
  menuNavIconEmoji: {
    fontSize: 24,
    textAlign: 'center',
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  menuNavGearIcon: {
    width: 28,
    height: 28,
  },
  menuNavMoreDotsIcon: {
    width: 28,
    height: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  menuNavMoreDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  menuNavTargetIcon: {
    width: 28,
    height: 28,
  },
  menuNavIconActive: {
    tintColor: '#4B3CC1',
  },
  menuNavIconInactive: {
    tintColor: '#FFFFFF',
  },
  menuNavTabLabel: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700',
  },
  menuNavTabLabelActive: {
    color: '#4B3CC1',
  },
  menuNavTabLabelInactive: {
    color: 'rgba(255, 255, 255, 0.92)',
  },
  menuGradientTopGlow: {
    position: 'absolute',
    top: 24,
    left: -60,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: 'rgba(130, 118, 255, 0.38)',
  },
  menuGradientBottomGlow: {
    position: 'absolute',
    right: -180,
    // Sit lower so color shows through the glass bottom nav (content “bleeds” under the bar).
    bottom: -140,
    width: 425,
    height: 425,
    borderRadius: 238,
    backgroundColor: 'rgba(42, 32, 145, 0.56)',
  },
  menuProfileButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuProfileIcon: {
    width: 32,
    height: 32,
  },
  menuMainActions: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 8,
    gap: 14,
  },
  weekdayBar: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  weekdayBarItem: {
    width: 34,
    alignItems: 'center',
  },
  weekdayBarLetter: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 6,
  },
  weekdayBarLetterActiveWorkout: {
    color: '#F59E0B',
  },
  weekdayBarLetterToday: {
    color: '#FFFFFF',
  },
  weekdayBarLetterInactive: {
    color: '#9AA1AC',
  },
  weekdayBarCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    backgroundColor: 'transparent',
  },
  weekdayBarCircleToday: {
    borderColor: '#FFFFFF',
  },
  weekdayBarCircleInactive: {
    borderColor: '#808894',
  },
  weekdayBarStreakLogo: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  menuGreetingText: {
    color: '#EEF1FF',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 4,
  },
  menuPrimaryButton: {
    width: '100%',
    borderRadius: 14,
    backgroundColor: '#5D55D8',
    paddingHorizontal: 16,
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuPrimaryButtonText: {
    color: '#EEF1FF',
    fontSize: 20,
    fontWeight: '500',
  },
  menuPrimaryIcon: {
    width: 52,
    height: 52,
    tintColor: '#EEF1FF',
  },
  menuSecondaryButton: {
    width: '100%',
    borderRadius: 14,
    backgroundColor: '#5950D0',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  menuSecondaryButtonText: {
    color: '#E8ECFF',
    fontSize: 20,
    fontWeight: '500',
  },
  profileHeaderRow: {
    width: '100%',
    minHeight: 52,
    marginTop: 26,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  profileCloseInlineButton: {
    position: 'absolute',
    left: 0,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileTitle: {
    color: '#EEF1FF',
    fontSize: 36,
    fontWeight: '800',
    alignSelf: 'center',
  },
  profileCard: {
    width: '100%',
    borderRadius: 20,
    backgroundColor: 'rgba(93, 85, 216, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 16,
  },
  profileLabel: {
    color: '#EEF1FF',
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  profileInput: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    backgroundColor: 'rgba(44, 36, 138, 0.65)',
    color: '#EEF1FF',
    fontSize: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  profileHint: {
    color: 'rgba(238, 241, 255, 0.8)',
    fontSize: 13,
    marginTop: 10,
  },
  profileSaveButton: {
    width: '100%',
    borderRadius: 14,
    backgroundColor: '#F8F8FF',
    paddingVertical: 14,
    alignItems: 'center',
  },
  profileSaveButtonText: {
    color: '#4B3CC1',
    fontSize: 18,
    fontWeight: '700',
  },
  profileScrollOuter: {
    flex: 1,
  },
  profileScrollContent: {
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 48,
  },
  heightSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    gap: 12,
  },
  heightSummaryValue: {
    flex: 1,
    color: '#EEF1FF',
    fontSize: 18,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  profileHeightEditLink: {
    color: '#C4C8FF',
    fontSize: 16,
    fontWeight: '800',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  profileHeightDoneButton: {
    alignSelf: 'center',
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  profileHeightDoneButtonText: {
    color: '#C4C8FF',
    fontSize: 15,
    fontWeight: '700',
  },
  heightPickerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginTop: 8,
    gap: 8,
  },
  heightPickerColumn: {
    flex: 1,
    minWidth: 0,
  },
  heightPickerCaption: {
    color: 'rgba(238, 241, 255, 0.9)',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  heightPickerCaptionSpaced: {
    marginBottom: 2,
  },
  profileHeightPickerWheel: {
    width: '100%',
  },
  profileHeightPickerWheelIOS: {
    height: 164,
  },
  profileHeightPickerItemStyle: {
    color: '#EEF1FF',
    fontSize: 20,
  },
  timerLabel: {
    color: '#B7BCC5',
    fontSize: 16,
    marginTop: 8,
  },
  timerValue: {
    color: '#FFFFFF',
    fontSize: 56,
    fontWeight: '700',
    marginTop: 6,
    marginBottom: 24,
  },
  dashboardHomeScroll: {
    flex: 1,
    width: '100%',
  },
  dashboardHomeScrollContent: {
    paddingBottom: 24,
    alignItems: 'stretch',
  },
  dashboardGreetingBlock: {
    width: '100%',
    marginBottom: 16,
  },
  dashboardSplitDayLine: {
    color: 'rgba(238, 241, 255, 0.82)',
    fontSize: 17,
    fontWeight: '600',
    marginTop: 2,
  },
  dashboardTargetMusclesScroll: {
    marginTop: 12,
    marginHorizontal: -4,
  },
  dashboardTargetMusclesScrollContent: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingVertical: 4,
    paddingLeft: 2,
    paddingRight: 16,
    gap: 10,
  },
  dashboardTargetMuscleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(28, 30, 36, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  /** Lighter rounded square behind the diagram only (sits on top of the chip). */
  dashboardTargetMuscleIconWell: {
    width: 76,
    height: 76,
    borderRadius: 14,
    backgroundColor: 'rgba(62, 65, 76, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardTargetMuscleIcon: {
    width: 64,
    height: 64,
  },
  dashboardTargetMuscleTextCol: {
    marginLeft: 8,
    flexShrink: 1,
    justifyContent: 'center',
  },
  dashboardTargetMuscleChipLabel: {
    color: 'rgba(238, 241, 255, 0.95)',
    fontSize: 15,
    fontWeight: '700',
  },
  dashboardEditSplitHint: {
    color: 'rgba(165, 180, 252, 0.95)',
    fontSize: 17,
    fontWeight: '600',
    marginTop: 2,
    textDecorationLine: 'underline',
  },
  dashboardCard: {
    width: '100%',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: 'rgba(93, 85, 216, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
  },
  dashboardCardTitle: {
    color: '#EEF1FF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  dashboardCardBody: {
    color: 'rgba(238, 241, 255, 0.88)',
    fontSize: 14,
    lineHeight: 20,
  },
  dashboardCardStat: {
    color: '#F8FAFC',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 4,
  },
  dashboardWeekProgressCard: {
    width: '100%',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: 'rgba(93, 85, 216, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    alignItems: 'stretch',
  },
  dashboardWeekProgressTitle: {
    color: '#EEF1FF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
    letterSpacing: 0.2,
    textAlign: 'left',
    alignSelf: 'stretch',
  },
  dashboardWeekProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  dashboardWeekProgressRingCol: {
    marginLeft: -6,
    alignItems: 'flex-start',
  },
  dashboardWeekProgressStreakCol: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'center',
    paddingLeft: 8,
    minWidth: 0,
  },
  dashboardWeekProgressStreakStack: {
    flexDirection: 'column',
    alignItems: 'stretch',
    width: '100%',
    gap: 8,
  },
  /** Same shell as `dashboardTargetMuscleChip` (muscle rows under split day). */
  dashboardWeekProgressStreakSubbox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(28, 30, 36, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    alignSelf: 'stretch',
    width: '100%',
    minWidth: 0,
  },
  dashboardWeekProgressStreakIcon: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  /** Same gray family as `dashboardTargetMuscleIconWell` when perfect streak is 0. */
  dashboardWeekProgressPerfectStreakIconZero: {
    tintColor: 'rgba(100, 104, 116, 0.95)',
    opacity: 0.92,
  },
  dashboardWeekProgressPerfectStreakZeroDigit: {
    color: 'rgba(118, 122, 134, 0.98)',
    fontSize: 26,
    fontWeight: '800',
  },
  dashboardWeekProgressPerfectStreakZeroLabel: {
    color: 'rgba(118, 122, 134, 0.98)',
    fontSize: 15,
    fontWeight: '700',
  },
  dashboardWeekProgressStreakTextBlock: {
    marginLeft: 10,
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  dashboardWeekProgressStreakLine: {
    flexWrap: 'wrap',
  },
  dashboardWeekProgressStreakNumber: {
    color: '#F59E0B',
    fontSize: 26,
    fontWeight: '800',
  },
  dashboardWeekProgressStreakNumberInactive: {
    color: 'rgba(238, 241, 255, 0.9)',
    fontSize: 26,
    fontWeight: '800',
  },
  dashboardWeekProgressStreakWords: {
    color: 'rgba(238, 241, 255, 0.9)',
    fontSize: 15,
    fontWeight: '700',
  },
  dashboardMuscleStatusCard: {
    width: '100%',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    backgroundColor: 'rgba(93, 85, 216, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    alignItems: 'stretch',
  },
  dashboardMuscleStatusTitle: {
    color: '#EEF1FF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  dashboardMuscleStatusLegendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
  },
  dashboardMuscleStatusDiagramsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
    width: '100%',
    minHeight: 156,
  },
  dashboardMuscleStatusDiagramHalf: {
    flex: 1,
    maxWidth: '50%',
    marginHorizontal: -4,
  },
  dashboardMuscleStatusLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dashboardMuscleStatusLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  dashboardMuscleStatusLegendLabel: {
    color: 'rgba(238, 241, 255, 0.88)',
    fontSize: 13,
    fontWeight: '600',
  },
  /** Active workout (solid screen) */
  activeWorkoutRoot: {
    flex: 1,
    backgroundColor: '#1A1A1C',
  },
  activeWorkoutHeaderPad: {
    paddingHorizontal: 16,
    alignItems: 'center',
    paddingBottom: 16,
  },
  activeWorkoutTimer: {
    color: '#EEF1FF',
    fontSize: 38,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    marginTop: 4,
    textAlign: 'center',
  },
  activeWorkoutScroll: {
    flex: 1,
    marginTop: 22,
  },
  activeWorkoutScrollInner: {
    paddingHorizontal: 16,
    paddingTop: 0,
    gap: 10,
  },
  activeWorkoutSwipeRowOuter: {
    position: 'relative',
    borderRadius: 14,
    overflow: 'hidden',
  },
  activeWorkoutSwipeDeleteWell: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'flex-end',
    justifyContent: 'center',
    backgroundColor: 'rgba(180, 35, 24, 0.95)',
  },
  activeWorkoutSwipeDeleteButton: {
    width: 80,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  activeWorkoutSwipeDeleteText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  activeWorkoutSwipeRowFront: {
    backgroundColor: '#1A1A1C',
  },
  activeWorkoutExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingLeft: 10,
    paddingRight: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(28, 30, 36, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  activeWorkoutExerciseIconWell: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: 'rgba(62, 65, 76, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeWorkoutExerciseIcon: {
    width: 44,
    height: 44,
  },
  activeWorkoutExerciseTextCol: {
    marginLeft: 12,
    flex: 1,
    minWidth: 0,
  },
  activeWorkoutExerciseTitle: {
    color: 'rgba(238, 241, 255, 0.95)',
    fontSize: 16,
    fontWeight: '700',
  },
  activeWorkoutExerciseSub: {
    marginTop: 4,
    color: 'rgba(238, 241, 255, 0.55)',
    fontSize: 13,
    fontWeight: '600',
  },
  activeWorkoutAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 4,
  },
  activeWorkoutAddIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(62, 65, 76, 0.98)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeWorkoutAddPlus: {
    color: 'rgba(238, 241, 255, 0.92)',
    fontSize: 26,
    fontWeight: '500',
    marginTop: -2,
  },
  activeWorkoutAddLabel: {
    marginLeft: 12,
    color: 'rgba(238, 241, 255, 0.88)',
    fontSize: 16,
    fontWeight: '700',
  },
  activeWorkoutBottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 36,
    paddingTop: 12,
    paddingHorizontal: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#1A1A1C',
  },
  activeWorkoutCircleButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5D55D8',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  activeWorkoutCircleButtonDisabled: {
    opacity: 0.38,
  },
  activeWorkoutCircleButtonText: {
    color: '#EEF1FF',
    fontSize: 22,
    fontWeight: '800',
  },
  activeWorkoutSheetCard: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(255, 255, 255, 0.16)',
    paddingBottom: 8,
    overflow: 'hidden',
  },
  activeWorkoutSheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  activeWorkoutSheetSearch: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 16,
  },
  activeWorkoutSheetExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  activeWorkoutSheetExerciseName: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    marginLeft: 12,
  },
  activeWorkoutLogHint: {
    fontSize: 13,
    marginBottom: 0,
    marginTop: 10,
    lineHeight: 18,
  },
  activeWorkoutLogSheetHeader: {
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 14,
    minHeight: 108,
    justifyContent: 'flex-start',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.12)',
  },
  activeWorkoutLogSheetDragPill: {
    alignSelf: 'center',
    width: 52,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
    marginBottom: 12,
  },
  activeWorkoutLogSheetHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  activeWorkoutLogSheetTitleInHeader: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    paddingRight: 4,
  },
  activeWorkoutLogSheetCloseTouch: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: -2,
  },
  activeWorkoutLogSheetCloseMark: {
    fontSize: 22,
    fontWeight: '600',
    color: '#4B3CC1',
  },
};
export default menuLayoutProfileStyles;
