import { StyleSheet, Platform } from 'react-native';
import { MAIN_NAV_TRACK_HEIGHT } from '../constants/layout';
import { GAME_THEME_DARK } from '../theme/gameTheme';

export function createMenuLayoutProfileStyles(theme) {
  const t = theme;
  return {
  mainTabsContentShell: {
    flex: 1,
    position: 'relative',
    backgroundColor: t.screenBg,
  },
  mainTabsScreenFade: {
    flex: 1,
    backgroundColor: t.screenBg,
  },
  mainTabsBottomFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 25,
  },
  mainTabsFloatingNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 30,
  },
  mainTabsFullBleedScroll: {
    flex: 1,
  },
  screenFadeContainer: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: t.screenBgAlt,
  },
  menuSafeArea: {
    backgroundColor: t.screenBg,
  },
  container: {
    padding: 20,
    paddingBottom: 32,
    alignItems: 'center',
  },
  workoutScreenWrapper: {
    flex: 1,
  },
  workoutScrollContent: {
    paddingTop: 44,
    paddingBottom: 140,
  },
  workoutSafeAreaLift: {
    paddingTop: 0,
  },
  workoutKeyboardAvoid: {
    flex: 1,
  },
  workoutGlowTop: {
    opacity: 0.55,
  },
  workoutGlowBottom: {
    opacity: 0.7,
  },
  workoutNotepadTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 8,
  },
  workoutHelpIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: t.helpButtonBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: t.helpButtonBorder,
  },
  workoutHelpIconText: {
    fontSize: 18,
    fontWeight: '800',
    color: t.navBack,
  },
  workoutWideButton: {
    marginTop: 4,
    marginBottom: 10,
  },
  workoutEndButton: {
    width: '100%',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 8,
  },
  workoutHelpModalBackdrop: {
    flex: 1,
    backgroundColor: t.overlayBg,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  workoutHelpModalCard: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 18,
    borderWidth: 1,
    padding: 18,
  },
  workoutHelpModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 12,
  },
  workoutHelpModalClose: {
    marginTop: 14,
    paddingVertical: 14,
    marginBottom: 0,
  },
  workoutCloseButtonMenu: {
    position: 'absolute',
    top: 4,
    left: 8,
    zIndex: 20,
    width: 44,
    height: 44,
    backgroundColor: t.cardBg,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: t.cardBorder,
  },
  /** Workout screen: open targets + muscle map sheet (top right). */
  workoutTargetsTopButton: {
    position: 'absolute',
    top: 4,
    right: 8,
    zIndex: 20,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 44,
    backgroundColor: t.cardBg,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: t.cardBorder,
  },
  workoutTargetsTopButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: t.navBack,
  },
  menuScreen: {
    flex: 1,
    backgroundColor: t.screenBg,
  },
  menuScreenWithHeaderSafeArea: {
    flex: 1,
    // Solid tint matches translucent menuTopBar over #1A1A1C (see MENU_TOP_BAR_STATUS_MATCH).
    backgroundColor: t.topBarStatusMatch,
  },
  menuBody: {
    flex: 1,
    backgroundColor: t.screenBg,
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 8,
  },
  /** Home menu: fixed rank bar + scrollable body below. */
  menuHomeShell: {
    flex: 1,
    backgroundColor: t.screenBg,
  },
  menuHomeScroll: {
    flex: 1,
  },
  menuHomeScrollContent: {
    paddingHorizontal: 22,
    paddingTop: 10,
  },
  menuTopBar: {
    width: 'auto',
    marginLeft: -22,
    marginRight: -22,
    marginTop: -14,
    minHeight: 78,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: t.topBarTranslucent,
    borderWidth: 1,
    borderColor: t.borderSubtle,
    borderTopWidth: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  menuRankTopBarHome: {
    marginTop: 0,
    marginLeft: 0,
    marginRight: 0,
    marginBottom: 0,
    zIndex: 10,
  },
  menuRankTopBarCompact: {
    minHeight: 56,
    paddingVertical: 10,
  },
  menuRankTopBarSpacer: {
    flex: 1,
    minWidth: 8,
  },
  menuRankProgressSlot: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  menuRankProgressBlock: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  menuRankProgressTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: t.surfaceMuted,
    borderWidth: 1,
    borderColor: t.borderFaint,
    overflow: 'hidden',
  },
  menuRankProgressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: t.primaryButtonBg,
    minWidth: 4,
  },
  menuRankProgressHint: {
    marginBottom: 4,
    color: t.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  menuRankBadgeWrap: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
  },
  menuRankBadgeWrapActive: {
    backgroundColor: t.surfaceMuted,
    borderWidth: 1,
    borderColor: t.cardBorderSubtle,
  },
  menuRankBadge: {
    width: 44,
    height: 44,
  },
  streakRankPanel: {
    width: '100%',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: t.cardBgTranslucent,
    borderWidth: 1,
    borderColor: t.borderFaint,
  },
  streakRankPanelTitle: {
    color: t.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 6,
  },
  streakRankPanelIntro: {
    color: t.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  streakRankCurrentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  streakRankCurrentBadge: {
    width: 64,
    height: 64,
    marginRight: 12,
  },
  streakRankCurrentTextCol: {
    flex: 1,
    minWidth: 0,
  },
  streakRankCurrentLabel: {
    color: t.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  streakRankCurrentSub: {
    color: t.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 2,
    marginBottom: 8,
  },
  streakRankProgressTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: t.surfaceMuted,
    borderWidth: 1,
    borderColor: t.borderFaint,
    overflow: 'hidden',
    marginBottom: 6,
  },
  streakRankProgressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: t.primaryButtonBg,
    minWidth: 4,
  },
  streakRankProgressHint: {
    color: t.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  streakRankLadderHeading: {
    color: t.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  streakRankLadderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: t.surfaceMuted,
    borderWidth: 1,
    borderColor: t.borderFaint,
  },
  streakRankLadderRowEarned: {
    borderColor: t.borderSubtle,
  },
  streakRankLadderRowCurrent: {
    borderColor: t.selectedExerciseBorder,
    backgroundColor: t.selectedExerciseBg,
  },
  streakRankLadderIcon: {
    width: 36,
    height: 36,
    marginRight: 10,
  },
  streakRankLadderIconLocked: {
    opacity: 0.35,
  },
  streakRankLadderTextCol: {
    flex: 1,
    minWidth: 0,
  },
  streakRankLadderName: {
    color: t.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  streakRankLadderNameLocked: {
    color: t.textMuted,
  },
  streakRankLadderWeeks: {
    color: t.textMuted,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 1,
  },
  streakRankLadderCheck: {
    color: t.successBright,
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 8,
  },
  menuTopBarDateText: {
    color: t.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  menuMoreTopBarSpacer: {
    width: 52,
    height: 52,
  },
  /** More tab: flat dark gray (no purple glow / glass rows). */
  menuMoreScreen: {
    flex: 1,
    backgroundColor: t.screenBg,
  },
  menuMoreHeader: {
    paddingHorizontal: 22,
    paddingTop: 14,
    paddingBottom: 12,
  },
  menuMoreHeaderTitle: {
    color: t.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  menuMoreScroll: {
    flex: 1,
  },
  menuMoreScrollContent: {
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 24,
  },
  menuMoreLinkGroup: {
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: t.surfaceRaised,
  },
  menuMoreSectionTitle: {
    color: t.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
  },
  menuMoreBodyText: {
    color: t.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  menuMoreIntro: {
    color: t.setLineMuted,
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 6,
  },
  menuMoreSectionHeading: {
    color: t.textSubtle,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    marginTop: 24,
    marginBottom: 8,
  },
  menuMoreSectionHeadingFirst: {
    marginTop: 0,
  },
  menuMoreLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    backgroundColor: t.surfaceRaised,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 0,
    borderRadius: 0,
    borderWidth: 0,
  },
  menuMoreLinkRowSeparator: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: t.borderFaint,
  },
  menuMoreLinkRowMuted: {
    opacity: 0.65,
  },
  menuMoreLinkIconWell: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: t.surfaceSunken,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  menuMoreLinkIcon: {
    width: 28,
    height: 28,
  },
  menuMoreLinkTextBlock: {
    flex: 1,
    paddingRight: 12,
    minWidth: 0,
  },
  menuMoreLinkTitle: {
    color: t.textPrimary,
    fontSize: 17,
    fontWeight: '600',
  },
  menuMoreLinkSubtitle: {
    color: t.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  menuMoreLinkChevron: {
    color: t.textSubtle,
    fontSize: 26,
    fontWeight: '300',
    marginTop: -2,
  },
  menuSubscreenNavTitle: {
    color: t.textPrimary,
    fontSize: 22,
    fontWeight: '800',
    alignSelf: 'center',
  },
  menuMoreEmphasisInline: {
    color: t.streakGold,
    fontWeight: '800',
  },
  menuMoreWeekdayBarInCard: {
    marginTop: 16,
  },
  // Shell only: no dark tray behind the bar — just spacing + the light pill row + FAB.
  menuBottomNav: {
    width: 'auto',
    marginLeft: -22,
    marginRight: -22,
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingTop: 12,
    position: 'relative',
    backgroundColor: 'transparent',
    overflow: 'visible',
  },
  menuBottomNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '96%',
    maxWidth: 420,
    position: 'relative',
    zIndex: 1,
  },
  menuNavFabWrap: {
    zIndex: 2,
    marginLeft: -26,
    width: 80,
    height: 84,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuNavFab: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: t.chipWellBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: t.chipWellBorder,
    boxShadow: `0px 6px 20px ${t.shadowTint}`,
    zIndex: 2,
    elevation: 2,
  },
  menuNavFabPlus: {
    fontSize: 42,
    lineHeight: 46,
    color: t.navAccent,
    fontWeight: '300',
    marginTop: -2,
  },
  menuNavTrack: {
    flex: 1,
    flexGrow: 1,
    minHeight: MAIN_NAV_TRACK_HEIGHT,
    height: MAIN_NAV_TRACK_HEIGHT,
    position: 'relative',
    backgroundColor: 'transparent',
    borderTopLeftRadius: 26,
    borderBottomLeftRadius: 26,
    borderTopRightRadius: 26,
    borderBottomRightRadius: 26,
    borderWidth: 1,
    borderColor: t.navTrackBorder,
    overflow: 'hidden',
  },
  menuNavTrackBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  menuNavTrackScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: t.navTrackBg,
  },
  menuNavTrackInner: {
    flex: 1,
    justifyContent: 'center',
    minHeight: MAIN_NAV_TRACK_HEIGHT,
    paddingLeft: 8,
    paddingRight: 34,
    position: 'relative',
    zIndex: 1,
    backgroundColor: 'transparent',
  },
  menuNavTabsRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    zIndex: 1,
  },
  menuNavTabTouchable: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  menuNavSlotAnchor: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  menuNavTabIndicator: {
    position: 'absolute',
    left: 0,
    borderRadius: 18,
    overflow: 'hidden',
    zIndex: 0,
    borderWidth: 1,
    borderColor: t.navTrackBorder,
    backgroundColor: 'transparent',
    boxShadow: `0px 2px 12px ${t.shadowTint}`,
  },
  menuNavTabIndicatorBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  /** Stronger frost than the tab strip scrim so the active tab reads as a denser glass pill. */
  menuNavTabIndicatorScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: t.navIndicatorBg,
  },
  menuNavIconEmoji: {
    fontSize: 24,
    textAlign: 'center',
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : {}),
  },
  menuNavGearIcon: {
    width: 28,
    height: 28,
  },
  menuNavMoreDotsIcon: {
    width: 28,
    height: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  menuNavMoreDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  menuNavTargetIcon: {
    width: 28,
    height: 28,
  },
  menuNavIconActive: {
    opacity: 1,
  },
  menuNavIconInactive: {
    opacity: 1,
  },
  menuNavTabLabel: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700',
  },
  menuNavTabLabelActive: {
    color: t.navAccent,
  },
  menuNavTabLabelInactive: {
    color: t.navIconInactive,
  },
  menuGradientTopGlow: {
    position: 'absolute',
    top: 24,
    left: -60,
    width: 360,
    height: 360,
    borderRadius: 180,
    backgroundColor: t.glowTop,
  },
  menuGradientBottomGlow: {
    position: 'absolute',
    right: -180,
    // Sit lower so color shows through the glass bottom nav (content “bleeds” under the bar).
    bottom: -140,
    width: 425,
    height: 425,
    borderRadius: 238,
    backgroundColor: t.glowBottom,
  },
  menuProfileButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: t.pillBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuProfileIcon: {
    width: 32,
    height: 32,
  },
  menuProfileLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  menuProfileButtonSmall: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: t.pillBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuProfileIconSmall: {
    width: 22,
    height: 22,
  },
  menuProfileLinkText: {
    color: t.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  menuProfileLinkChevron: {
    color: t.textSecondary,
    fontSize: 18,
    fontWeight: '600',
    marginTop: -1,
  },
  menuMainActions: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 8,
    gap: 14,
  },
  weekdayBar: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  weekdayBarItem: {
    width: 34,
    alignItems: 'center',
  },
  weekdayBarLetter: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 6,
  },
  weekdayBarLetterActiveWorkout: {
    color: t.streakGold,
  },
  weekdayBarLetterToday: {
    color: t.cardBg,
  },
  weekdayBarLetterInactive: {
    color: t.textMuted,
  },
  weekdayBarCircle: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    backgroundColor: 'transparent',
  },
  weekdayBarCircleToday: {
    borderColor: t.cardBg,
  },
  weekdayBarCircleInactive: {
    borderColor: t.textMuted,
  },
  weekdayBarStreakLogo: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  menuGreetingText: {
    color: t.textPrimary,
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 4,
  },
  menuPrimaryButton: {
    width: '100%',
    borderRadius: 18,
    backgroundColor: t.primaryButtonBg,
    paddingHorizontal: 16,
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuPrimaryButtonText: {
    color: t.primaryButtonText,
    fontSize: 20,
    fontWeight: '500',
  },
  menuPrimaryIcon: {
    width: 52,
    height: 52,
  },
  menuSecondaryButton: {
    width: '100%',
    borderRadius: 18,
    backgroundColor: t.secondaryButtonBg,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  menuSecondaryButtonText: {
    color: t.secondaryButtonText,
    fontSize: 20,
    fontWeight: '500',
  },
  profileHeaderRow: {
    width: '100%',
    minHeight: 52,
    marginTop: 26,
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  profileCloseInlineButton: {
    position: 'absolute',
    left: 0,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: t.cardBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileTitle: {
    color: t.textPrimary,
    fontSize: 36,
    fontWeight: '800',
    alignSelf: 'center',
  },
  profileCard: {
    width: '100%',
    borderRadius: 20,
    backgroundColor: t.cardBg,
    borderWidth: 1,
    borderColor: t.cardBorderSubtle,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 16,
  },
  profileLabel: {
    color: t.textPrimary,
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  profileInput: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: t.inputBorder,
    backgroundColor: t.inputBg,
    color: t.textPrimary,
    fontSize: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  profileHint: {
    color: t.textSecondary,
    fontSize: 13,
    marginTop: 10,
  },
  profileSaveButton: {
    width: '100%',
    borderRadius: 18,
    backgroundColor: t.primaryButtonBg,
    paddingVertical: 14,
    alignItems: 'center',
  },
  profileSaveButtonText: {
    color: t.primaryButtonText,
    fontSize: 18,
    fontWeight: '700',
  },
  profileHeroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 16,
  },
  profileHeroIconWell: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: t.pillBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: t.cardBorderSubtle,
  },
  profileHeroIcon: {
    width: 32,
    height: 32,
  },
  profileHeroTextCol: {
    flex: 1,
    minWidth: 0,
  },
  profileHeroName: {
    color: t.textPrimary,
    fontSize: 22,
    fontWeight: '800',
  },
  profileHeroSubtitle: {
    color: t.textSecondary,
    fontSize: 14,
    marginTop: 4,
    fontWeight: '600',
  },
  profileStatsCardTitle: {
    color: t.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  profileStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  profileStatCell: {
    width: '47%',
    minWidth: 120,
    flexGrow: 1,
    borderRadius: 12,
    backgroundColor: t.surfaceMuted,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: t.borderFaint,
  },
  profileStatLabel: {
    color: t.textMuted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  profileStatValue: {
    color: t.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  profileScrollOuter: {
    flex: 1,
  },
  profileScrollContent: {
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 48,
  },
  heightSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    gap: 12,
  },
  heightSummaryValue: {
    flex: 1,
    color: t.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  profileHeightEditLink: {
    color: t.textMuted,
    fontSize: 16,
    fontWeight: '800',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  profileHeightDoneButton: {
    alignSelf: 'center',
    marginTop: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  profileHeightDoneButtonText: {
    color: t.textMuted,
    fontSize: 15,
    fontWeight: '700',
  },
  heightPickerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginTop: 8,
    gap: 8,
  },
  heightPickerColumn: {
    flex: 1,
    minWidth: 0,
  },
  heightPickerCaption: {
    color: t.textPrimary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  heightPickerCaptionSpaced: {
    marginBottom: 2,
  },
  profileHeightPickerWheel: {
    width: '100%',
  },
  profileHeightPickerWheelIOS: {
    height: 164,
  },
  profileHeightPickerItemStyle: {
    color: t.textPrimary,
    fontSize: 20,
  },
  timerLabel: {
    color: t.textMuted,
    fontSize: 16,
    marginTop: 8,
  },
  timerValue: {
    color: t.cardBg,
    fontSize: 56,
    fontWeight: '700',
    marginTop: 6,
    marginBottom: 24,
  },
  dashboardHomeScroll: {
    flex: 1,
    width: '100%',
  },
  dashboardHomeScrollContent: {
    paddingBottom: 24,
    alignItems: 'stretch',
  },
  dashboardGreetingBlock: {
    width: '100%',
    marginBottom: 16,
  },
  dashboardSplitDayLine: {
    color: t.setLineMuted,
    fontSize: 17,
    fontWeight: '600',
    marginTop: 2,
  },
  dashboardTargetMusclesScroll: {
    marginTop: 12,
    marginHorizontal: -4,
  },
  dashboardTargetMusclesScrollContent: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingVertical: 4,
    paddingLeft: 2,
    paddingRight: 16,
    gap: 10,
  },
  dashboardTargetMuscleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 12,
    borderRadius: 18,
    backgroundColor: t.moreRowBg,
    borderWidth: 1,
    borderColor: t.navTrackBg,
  },
  /** Lighter rounded square behind the diagram only (sits on top of the chip). */
  dashboardTargetMuscleIconWell: {
    width: 76,
    height: 76,
    borderRadius: 18,
    backgroundColor: t.surfaceRaised,
    borderWidth: 1,
    borderColor: t.borderFaint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardTargetMuscleIcon: {
    width: 64,
    height: 64,
  },
  dashboardTargetMuscleTextCol: {
    marginLeft: 8,
    flexShrink: 1,
    justifyContent: 'center',
  },
  dashboardTargetMuscleChipLabel: {
    color: t.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  dashboardEditSplitHint: {
    color: t.cardBg,
    fontSize: 17,
    fontWeight: '600',
    marginTop: 2,
  },
  dashboardCard: {
    width: '100%',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: t.cardBgTranslucent,
    borderWidth: 1,
    borderColor: t.borderFaint,
  },
  dashboardCardTitle: {
    color: t.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  dashboardCardBody: {
    color: t.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  dashboardCardStat: {
    color: t.textPrimary,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 4,
  },
  dashboardWeekProgressCard: {
    width: '100%',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: t.cardBgTranslucent,
    borderWidth: 2,
    borderColor: t.cardBorderCoral,
    alignItems: 'stretch',
  },
  dashboardWeekProgressTitle: {
    color: t.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
    letterSpacing: 0.2,
    textAlign: 'left',
    alignSelf: 'stretch',
  },
  dashboardWeekProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  dashboardWeekProgressRingCol: {
    marginLeft: -6,
    alignItems: 'flex-start',
  },
  dashboardWeekProgressStreakCol: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'center',
    paddingLeft: 8,
    minWidth: 0,
  },
  dashboardWeekProgressStreakStack: {
    flexDirection: 'column',
    alignItems: 'stretch',
    width: '100%',
    gap: 8,
  },
  /** Same shell as `dashboardTargetMuscleChip` (muscle rows under split day). */
  dashboardWeekProgressStreakSubbox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 12,
    borderRadius: 18,
    backgroundColor: t.moreRowBg,
    borderWidth: 1,
    borderColor: t.navTrackBg,
    alignSelf: 'stretch',
    width: '100%',
    minWidth: 0,
  },
  dashboardWeekProgressStreakIcon: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  /** Same gray family as `dashboardTargetMuscleIconWell` when perfect streak is 0. */
  dashboardWeekProgressPerfectStreakIconZero: {
    opacity: 0.4,
  },
  dashboardWeekProgressPerfectStreakZeroDigit: {
    color: t.zeroStateText,
    fontSize: 26,
    fontWeight: '800',
  },
  dashboardWeekProgressPerfectStreakZeroLabel: {
    color: t.zeroStateText,
    fontSize: 15,
    fontWeight: '700',
  },
  dashboardWeekProgressStreakTextBlock: {
    marginLeft: 10,
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  dashboardWeekProgressStreakLine: {
    flexWrap: 'wrap',
  },
  dashboardWeekProgressMetricRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  dashboardWeekProgressNumberSlot: {
    minWidth: 22,
    marginRight: 2,
  },
  dashboardWeekProgressWordStack: {
    marginTop: 1,
  },
  dashboardWeekProgressStreakNumber: {
    color: t.streakGold,
    fontSize: 26,
    fontWeight: '800',
  },
  dashboardWeekProgressStreakNumberInactive: {
    color: t.textPrimary,
    fontSize: 26,
    fontWeight: '800',
  },
  dashboardWeekProgressStreakWords: {
    color: t.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  dashboardMuscleStatusCard: {
    width: '100%',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    backgroundColor: t.cardBgTranslucent,
    borderWidth: 2,
    borderColor: t.cardBorderSky,
    alignItems: 'stretch',
  },
  dashboardMuscleStatusTitle: {
    color: t.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  dashboardMuscleStatusLegendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
  },
  dashboardMuscleStatusDiagramsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
    width: '100%',
    minHeight: 156,
  },
  dashboardMuscleStatusDiagramHalf: {
    flex: 1,
    maxWidth: '50%',
    marginHorizontal: -4,
  },
  dashboardMuscleStatusLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dashboardMuscleStatusLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  dashboardMuscleStatusLegendLabel: {
    color: t.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  /** Active workout (solid screen) */
  activeWorkoutRoot: {
    flex: 1,
    backgroundColor: t.screenBg,
  },
  activeWorkoutHeaderPad: {
    paddingHorizontal: 16,
    alignItems: 'center',
    paddingBottom: 16,
  },
  activeWorkoutTimer: {
    color: t.textPrimary,
    fontSize: 38,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    marginTop: 4,
    textAlign: 'center',
  },
  workoutCelebrationBannerHost: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 30,
    elevation: 24,
  },
  workoutCelebrationBannerWrap: {
    marginHorizontal: 16,
  },
  workoutCelebrationBannerCard: {
    flexDirection: 'row',
    borderRadius: 18,
    borderWidth: 1,
    backgroundColor: t.moreRowBg,
    overflow: 'hidden',
    shadowColor: t.celebrationShadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  workoutCelebrationAccentBar: {
    width: 5,
  },
  workoutCelebrationTextCol: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  workoutCelebrationTitle: {
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  workoutCelebrationSubtitle: {
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  activeWorkoutScroll: {
    flex: 1,
    marginTop: 22,
  },
  activeWorkoutScrollInner: {
    paddingHorizontal: 16,
    paddingTop: 0,
    gap: 10,
  },
  activeWorkoutSwipeRowOuter: {
    position: 'relative',
    borderRadius: 18,
    overflow: 'hidden',
  },
  activeWorkoutSwipeDeleteWell: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'flex-end',
    justifyContent: 'center',
    backgroundColor: t.swipeDeleteBg,
  },
  activeWorkoutSwipeDeleteButton: {
    width: 80,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  activeWorkoutSwipeDeleteText: {
    color: t.cardBg,
    fontSize: 14,
    fontWeight: '800',
  },
  activeWorkoutSwipeRowFront: {
    backgroundColor: t.screenBg,
  },
  activeWorkoutExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingLeft: 10,
    paddingRight: 14,
    borderRadius: 18,
    backgroundColor: t.moreRowBg,
    borderWidth: 1,
    borderColor: t.navTrackBg,
  },
  activeWorkoutExerciseIconWell: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: t.surfaceRaised,
    borderWidth: 1,
    borderColor: t.borderFaint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeWorkoutExerciseIcon: {
    width: 44,
    height: 44,
  },
  activeWorkoutExerciseTextCol: {
    marginLeft: 12,
    flex: 1,
    minWidth: 0,
  },
  activeWorkoutExerciseTitle: {
    color: t.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  activeWorkoutExerciseSub: {
    marginTop: 4,
    color: t.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  activeWorkoutAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
    marginBottom: 4,
  },
  activeWorkoutAddIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: t.surfaceRaised,
    borderWidth: 1,
    borderColor: t.borderFaint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeWorkoutAddPlus: {
    color: t.textSecondary,
    fontSize: 26,
    fontWeight: '500',
    marginTop: -2,
  },
  activeWorkoutAddLabel: {
    marginLeft: 12,
    color: t.textSecondary,
    fontSize: 16,
    fontWeight: '700',
  },
  activeWorkoutBottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 36,
    paddingTop: 12,
    paddingHorizontal: 24,
    borderTopWidth: 1,
    borderTopColor: t.borderFaint,
    backgroundColor: t.screenBg,
  },
  activeWorkoutCircleButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: t.primaryButtonBg,
    borderWidth: 1,
    borderColor: t.cardBorderSubtle,
  },
  activeWorkoutCircleButtonDisabled: {
    opacity: 0.38,
  },
  activeWorkoutCircleButtonText: {
    color: t.textPrimary,
    fontSize: 22,
    fontWeight: '800',
  },
  activeWorkoutSheetCard: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: t.borderSubtle,
    paddingBottom: 8,
    overflow: 'hidden',
  },
  activeWorkoutSheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  activeWorkoutSheetSearch: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 16,
  },
  activeWorkoutSheetExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: t.borderFaint,
  },
  activeWorkoutSheetExerciseName: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    marginLeft: 12,
  },
  activeWorkoutLogHint: {
    fontSize: 13,
    marginBottom: 0,
    marginTop: 10,
    lineHeight: 18,
  },
  activeWorkoutLogSheetHeader: {
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 14,
    minHeight: 108,
    justifyContent: 'flex-start',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: t.borderFaint,
  },
  activeWorkoutLogSheetDragPill: {
    alignSelf: 'center',
    width: 52,
    height: 6,
    borderRadius: 3,
    backgroundColor: t.navTrackBorder,
    marginBottom: 12,
  },
  activeWorkoutLogSheetHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  activeWorkoutLogSheetTitleInHeader: {
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    paddingRight: 4,
  },
  activeWorkoutLogSheetCloseTouch: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: -2,
  },
  activeWorkoutLogSheetCloseMark: {
    fontSize: 22,
    fontWeight: '600',
    color: t.navBack,
  },
  activeWorkoutLogSheetToolbarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 10,
  },
  logSheetToolbarButton: {
    minWidth: 88,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: t.borderFaint,
    backgroundColor: t.surfaceMuted,
  },
  logSheetToolbarButtonHistory: {
    alignItems: 'flex-start',
  },
  logSheetToolbarButtonRest: {
    alignItems: 'flex-end',
    marginLeft: 'auto',
  },
  logSheetToolbarButtonLabel: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  logSheetToolbarButtonValue: {
    fontSize: 17,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  logSheetRestPickerBackdrop: {
    flex: 1,
    backgroundColor: t.overlayBgHeavy,
  },
  logSheetRestPickerSheet: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 16,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: t.borderSubtle,
  },
  logSheetRestPickerTitle: {
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  logSheetRestPickerWheels: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  logSheetRestPickerColumn: {
    flex: 1,
    maxWidth: 140,
    alignItems: 'center',
  },
  logSheetRestPickerCaption: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
  },
  logSheetRestPickerWheel: {
    width: '100%',
    height: 160,
  },
  logSheetRestPickerWheelIOS: {
    height: 180,
  },
  logSheetRestPickerItem: {
    fontSize: 20,
    color: t.textPrimary,
  },
  logSheetHistoryRow: {
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: t.borderSubtle,
  },
  logSheetHistoryRowText: {
    fontSize: 15,
    lineHeight: 21,
  },
  logSheetHistoryEmpty: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    alignItems: 'center',
  },
  logSheetSaveFooter: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
  },
  onboardingScreen: {
    flex: 1,
    backgroundColor: t.navBack,
  },
  onboardingScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: 8,
    paddingBottom: 24,
  },
  onboardingStepLabel: {
    color: t.textSecondary,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  onboardingTitle: {
    color: t.textPrimary,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 10,
  },
  onboardingBody: {
    color: t.textSecondary,
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 20,
  },
  onboardingFooter: {
    paddingHorizontal: 22,
    paddingBottom: 24,
    paddingTop: 8,
    gap: 10,
  },
  onboardingPrimaryButton: {
    width: '100%',
    borderRadius: 18,
    backgroundColor: t.textPrimary,
    paddingVertical: 14,
    alignItems: 'center',
  },
  onboardingPrimaryButtonDisabled: {
    opacity: 0.45,
  },
  onboardingPrimaryButtonText: {
    color: t.navBack,
    fontSize: 18,
    fontWeight: '700',
  },
  onboardingSecondaryButton: {
    width: '100%',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: t.cardBorder,
    paddingVertical: 12,
    alignItems: 'center',
  },
  onboardingSecondaryButtonText: {
    color: t.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  onboardingWelcomeIcon: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: t.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  onboardingWelcomeIconText: {
    fontSize: 34,
  },
  };
}

/** Static fallback for unmigrated imports — light candy theme. */
export default createMenuLayoutProfileStyles(GAME_THEME_DARK);
